/*
Oceanengine Open Api

巨量引擎开放平台 Open Api


*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package main

import (
	"context"
	"encoding/json"
	"fmt"
	"io"
	"log"

	ad_open_sdk_go "github.com/oceanengine/ad_open_sdk_go"
	"github.com/oceanengine/ad_open_sdk_go/config"
	. "github.com/oceanengine/ad_open_sdk_go/models"
)

type ApiOpenApiV10QianchuanAwemeUniPromotionEstimateEffectGetRequestExample struct {
	AdvertiserId    int64   `json:"advertiser_id"`
	AwemeId         int64   `json:"aweme_id"`
	ProductId       int64   `json:"product_id"`
	DeliveryTime    float64 `json:"delivery_time"`
	Amount          int64   `json:"amount"`
	AddAmount       int64   `json:"add_amount,omitempty"`
	AddDeliveryTime float64 `json:"add_delivery_time,omitempty"`
}

// url: https://api.oceanengine.com/open_api/v1.0/qianchuan/aweme/uni_promotion/estimate/effect/ Get
func main() {
	const demoreq = ``
	const accessToken = "ACCESS_TOKEN"
	ctx := context.Background()

	configuration := config.NewConfiguration()
	apiClient := ad_open_sdk_go.Init(configuration)
	apiClient.SetLogEnable(true)

	var request ApiOpenApiV10QianchuanAwemeUniPromotionEstimateEffectGetRequestExample
	err := json.Unmarshal([]byte(demoreq), &request)
	if err != nil {
		log.Fatal(err)
	}

	resp, httpRes, err := apiClient.QianchuanAwemeUniPromotionEstimateEffectV10Api().
		Get(ctx).
		AccessToken(accessToken).
		AdvertiserId(request.AdvertiserId).AwemeId(request.AwemeId).ProductId(request.ProductId).DeliveryTime(request.DeliveryTime).Amount(request.Amount).AddAmount(request.AddAmount).AddDeliveryTime(request.AddDeliveryTime).
		Execute()
	fmt.Println(ToJsonString(resp))
	resBytes, _ := io.ReadAll(httpRes.Body)
	fmt.Println(string(resBytes))
	fmt.Println(err)

}
