/*
Oceanengine Open Api

巨量引擎开放平台 Open Api


*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"context"
	"net/http"
	"net/url"

	"github.com/oceanengine/ad_open_sdk_go/config"

	"github.com/oceanengine/ad_open_sdk_go/models"
)

// ToolsAgreementListV30ApiService ToolsAgreementListV30Api service
type ToolsAgreementListV30ApiService service

type ApiOpenApiV30ToolsAgreementListGetRequest struct {
	ctx          context.Context
	ApiService   *ToolsAgreementListV30ApiService
	advertiserId *int64
	types        *[]*models.ToolsAgreementListV30Types
	signStatus   *models.ToolsAgreementListV30SignStatus
}

// 广告主id
func (r *ApiOpenApiV30ToolsAgreementListGetRequest) AdvertiserId(advertiserId int64) *ApiOpenApiV30ToolsAgreementListGetRequest {
	r.advertiserId = &advertiserId
	return r
}

// 通知类型列表，不传则返回全部配置类型
func (r *ApiOpenApiV30ToolsAgreementListGetRequest) Types(types []*models.ToolsAgreementListV30Types) *ApiOpenApiV30ToolsAgreementListGetRequest {
	r.types = &types
	return r
}

// 签署状态，不传则不过滤；0-未签署，1-已签署
func (r *ApiOpenApiV30ToolsAgreementListGetRequest) SignStatus(signStatus models.ToolsAgreementListV30SignStatus) *ApiOpenApiV30ToolsAgreementListGetRequest {
	r.signStatus = &signStatus
	return r
}

func (r *ApiOpenApiV30ToolsAgreementListGetRequest) Execute() (*models.ToolsAgreementListV30Response, *http.Response, error) {
	return r.ApiService.getExecute(r)
}

func (r *ApiOpenApiV30ToolsAgreementListGetRequest) AccessToken(accessToken string) *ApiOpenApiV30ToolsAgreementListGetRequest {
	r.ctx = context.WithValue(r.ctx, config.ContextAccessToken, accessToken)
	return r
}

func (r *ApiOpenApiV30ToolsAgreementListGetRequest) WithLog(enable bool) *ApiOpenApiV30ToolsAgreementListGetRequest {
	if enable {
		r.ctx = context.WithValue(r.ctx, config.ContextEnableLog, true)
	}
	return r
}

/*
OpenApiV30ToolsAgreementListGet Method for OpenApiV30ToolsAgreementListGet

查询当前投放账号下的协议列表，包括待签署协议、需重新签署协议、已签署协议

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@return ApiOpenApiV30ToolsAgreementListGetRequest
*/
func (a *ToolsAgreementListV30ApiService) Get(ctx context.Context) *ApiOpenApiV30ToolsAgreementListGetRequest {
	return &ApiOpenApiV30ToolsAgreementListGetRequest{
		ApiService: a,
		ctx:        ctx,
	}
}

// Execute executes the request
//
//	@return ToolsAgreementListV30Response
func (a *ToolsAgreementListV30ApiService) getExecute(r *ApiOpenApiV30ToolsAgreementListGetRequest) (*models.ToolsAgreementListV30Response, *http.Response, error) {
	var (
		localVarHTTPMethod  = http.MethodGet
		localVarPostBody    interface{}
		formFiles           map[string]*models.FormFileInfo
		localVarReturnValue *models.ToolsAgreementListV30Response
	)

	r.ctx = a.client.prepareCtx(r.ctx)

	localBasePath := a.client.Cfg.GetBasePath()

	localVarPath := localBasePath + "/open_api/v3.0/tools/agreement/list/"

	localVarHeaderParams := make(map[string]string)
	formFiles = make(map[string]*models.FormFileInfo)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}
	if r.advertiserId == nil {
		return localVarReturnValue, nil, ReportError("advertiserId is required and must be specified")
	}

	parameterAddToHeaderOrQuery(localVarQueryParams, "advertiser_id", r.advertiserId)
	if r.types != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "types", r.types)
	}
	if r.signStatus != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "sign_status", r.signStatus)
	}
	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.call(r.ctx, req, &localVarReturnValue)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}
	return localVarReturnValue, localVarHTTPResponse, nil
}
