/*
Oceanengine Open Api

巨量引擎开放平台 Open Api


*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"context"
	"net/http"
	"net/url"

	"github.com/oceanengine/ad_open_sdk_go/config"
	. "github.com/oceanengine/ad_open_sdk_go/models"
)

// CreativeDetailGetV30ApiService CreativeDetailGetV30Api service
type CreativeDetailGetV30ApiService service

type ApiOpenApiV30CreativeDetailGetGetRequest struct {
	ctx          context.Context
	ApiService   *CreativeDetailGetV30ApiService
	advertiserId *int64
	adId         *int64
}

func (r *ApiOpenApiV30CreativeDetailGetGetRequest) AdvertiserId(advertiserId int64) *ApiOpenApiV30CreativeDetailGetGetRequest {
	r.advertiserId = &advertiserId
	return r
}

func (r *ApiOpenApiV30CreativeDetailGetGetRequest) AdId(adId int64) *ApiOpenApiV30CreativeDetailGetGetRequest {
	r.adId = &adId
	return r
}

func (r *ApiOpenApiV30CreativeDetailGetGetRequest) Execute() (*CreativeDetailGetV30Response, *http.Response, error) {
	return r.ApiService.getExecute(r)
}

func (r *ApiOpenApiV30CreativeDetailGetGetRequest) AccessToken(accessToken string) *ApiOpenApiV30CreativeDetailGetGetRequest {
	r.ctx = context.WithValue(r.ctx, config.ContextAccessToken, accessToken)
	return r
}

func (r *ApiOpenApiV30CreativeDetailGetGetRequest) WithLog(enable bool) *ApiOpenApiV30CreativeDetailGetGetRequest {
	if enable {
		r.ctx = context.WithValue(r.ctx, config.ContextEnableLog, true)
	}
	return r
}

/*
OpenApiV30CreativeDetailGetGet Method for OpenApiV30CreativeDetailGetGet

给定计划id，查询计划的创意设置详细信息

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@return ApiOpenApiV30CreativeDetailGetGetRequest
*/
func (a *CreativeDetailGetV30ApiService) Get(ctx context.Context) *ApiOpenApiV30CreativeDetailGetGetRequest {
	return &ApiOpenApiV30CreativeDetailGetGetRequest{
		ApiService: a,
		ctx:        ctx,
	}
}

// Execute executes the request
//
//	@return CreativeDetailGetV30Response
func (a *CreativeDetailGetV30ApiService) getExecute(r *ApiOpenApiV30CreativeDetailGetGetRequest) (*CreativeDetailGetV30Response, *http.Response, error) {
	var (
		localVarHTTPMethod  = http.MethodGet
		localVarPostBody    interface{}
		formFiles           map[string]*FormFileInfo
		localVarReturnValue *CreativeDetailGetV30Response
	)

	r.ctx = a.client.prepareCtx(r.ctx)

	localBasePath := a.client.Cfg.GetBasePath()

	localVarPath := localBasePath + "/open_api/v3.0/creative/detail/get/"

	localVarHeaderParams := make(map[string]string)
	formFiles = make(map[string]*FormFileInfo)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}
	if r.advertiserId == nil {
		return localVarReturnValue, nil, ReportError("advertiserId is required and must be specified")
	}
	if r.adId == nil {
		return localVarReturnValue, nil, ReportError("adId is required and must be specified")
	}
	if *r.adId < 1 {
		return localVarReturnValue, nil, ReportError("adId must be greater than 1")
	}

	parameterAddToHeaderOrQuery(localVarQueryParams, "advertiser_id", r.advertiserId)
	parameterAddToHeaderOrQuery(localVarQueryParams, "ad_id", r.adId)
	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.call(r.ctx, req, &localVarReturnValue)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}
	return localVarReturnValue, localVarHTTPResponse, nil
}
