/*
Oceanengine Open Api

巨量引擎开放平台 Open Api


*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"context"
	"net/http"
	"net/url"

	"github.com/oceanengine/ad_open_sdk_go/config"
	. "github.com/oceanengine/ad_open_sdk_go/models"
)

// ChargeInfoOrderNoGetV30ApiService ChargeInfoOrderNoGetV30Api service
type ChargeInfoOrderNoGetV30ApiService service

type ApiOpenApiV30ChargeInfoOrderNoGetGetRequest struct {
	ctx            context.Context
	ApiService     *ChargeInfoOrderNoGetV30ApiService
	advertiserId   *int64
	outOrderNo     *string
	chargeTargetId *int64
}

func (r *ApiOpenApiV30ChargeInfoOrderNoGetGetRequest) AdvertiserId(advertiserId int64) *ApiOpenApiV30ChargeInfoOrderNoGetGetRequest {
	r.advertiserId = &advertiserId
	return r
}

// 三方单号,（包括商户单号、商家订单号、flowId、苹果单号等）
func (r *ApiOpenApiV30ChargeInfoOrderNoGetGetRequest) OutOrderNo(outOrderNo string) *ApiOpenApiV30ChargeInfoOrderNoGetGetRequest {
	r.outOrderNo = &outOrderNo
	return r
}

// 充值账户，传入时仅返回属于该账户的查询结果
func (r *ApiOpenApiV30ChargeInfoOrderNoGetGetRequest) ChargeTargetId(chargeTargetId int64) *ApiOpenApiV30ChargeInfoOrderNoGetGetRequest {
	r.chargeTargetId = &chargeTargetId
	return r
}

func (r *ApiOpenApiV30ChargeInfoOrderNoGetGetRequest) Execute() (*ChargeInfoOrderNoGetV30Response, *http.Response, error) {
	return r.ApiService.getExecute(r)
}

func (r *ApiOpenApiV30ChargeInfoOrderNoGetGetRequest) AccessToken(accessToken string) *ApiOpenApiV30ChargeInfoOrderNoGetGetRequest {
	r.ctx = context.WithValue(r.ctx, config.ContextAccessToken, accessToken)
	return r
}

func (r *ApiOpenApiV30ChargeInfoOrderNoGetGetRequest) WithLog(enable bool) *ApiOpenApiV30ChargeInfoOrderNoGetGetRequest {
	if enable {
		r.ctx = context.WithValue(r.ctx, config.ContextEnableLog, true)
	}
	return r
}

/*
OpenApiV30ChargeInfoOrderNoGetGet Method for OpenApiV30ChargeInfoOrderNoGetGet

按三方单号查询充值信息

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@return ApiOpenApiV30ChargeInfoOrderNoGetGetRequest
*/
func (a *ChargeInfoOrderNoGetV30ApiService) Get(ctx context.Context) *ApiOpenApiV30ChargeInfoOrderNoGetGetRequest {
	return &ApiOpenApiV30ChargeInfoOrderNoGetGetRequest{
		ApiService: a,
		ctx:        ctx,
	}
}

// Execute executes the request
//
//	@return ChargeInfoOrderNoGetV30Response
func (a *ChargeInfoOrderNoGetV30ApiService) getExecute(r *ApiOpenApiV30ChargeInfoOrderNoGetGetRequest) (*ChargeInfoOrderNoGetV30Response, *http.Response, error) {
	var (
		localVarHTTPMethod  = http.MethodGet
		localVarPostBody    interface{}
		formFiles           map[string]*FormFileInfo
		localVarReturnValue *ChargeInfoOrderNoGetV30Response
	)

	r.ctx = a.client.prepareCtx(r.ctx)

	localBasePath := a.client.Cfg.GetBasePath()

	localVarPath := localBasePath + "/open_api/v3.0/charge_info_order_no/get/"

	localVarHeaderParams := make(map[string]string)
	formFiles = make(map[string]*FormFileInfo)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}
	if r.advertiserId == nil {
		return localVarReturnValue, nil, ReportError("advertiserId is required and must be specified")
	}
	if r.outOrderNo == nil {
		return localVarReturnValue, nil, ReportError("outOrderNo is required and must be specified")
	}

	parameterAddToHeaderOrQuery(localVarQueryParams, "advertiser_id", r.advertiserId)
	parameterAddToHeaderOrQuery(localVarQueryParams, "out_order_no", r.outOrderNo)
	if r.chargeTargetId != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "charge_target_id", r.chargeTargetId)
	}
	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.call(r.ctx, req, &localVarReturnValue)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}
	return localVarReturnValue, localVarHTTPResponse, nil
}
