/*
Oceanengine Open Api

巨量引擎开放平台 Open Api


*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"context"
	"net/http"
	"net/url"

	"github.com/oceanengine/ad_open_sdk_go/config"
	. "github.com/oceanengine/ad_open_sdk_go/models"
)

// BrandMaWarningOrderListV30ApiService BrandMaWarningOrderListV30Api service
type BrandMaWarningOrderListV30ApiService service

type ApiOpenApiV30BrandMaWarningOrderListGetRequest struct {
	ctx           context.Context
	ApiService    *BrandMaWarningOrderListV30ApiService
	advertiserIds *[]int64
	startTime     *string
	endTime       *string
}

// 目标广告主 ID
func (r *ApiOpenApiV30BrandMaWarningOrderListGetRequest) AdvertiserIds(advertiserIds []int64) *ApiOpenApiV30BrandMaWarningOrderListGetRequest {
	r.advertiserIds = &advertiserIds
	return r
}

// 预定单投放开始时间：yyyy-MM-dd
func (r *ApiOpenApiV30BrandMaWarningOrderListGetRequest) StartTime(startTime string) *ApiOpenApiV30BrandMaWarningOrderListGetRequest {
	r.startTime = &startTime
	return r
}

// 预定单投放结束时间：yyyy-MM-dd
func (r *ApiOpenApiV30BrandMaWarningOrderListGetRequest) EndTime(endTime string) *ApiOpenApiV30BrandMaWarningOrderListGetRequest {
	r.endTime = &endTime
	return r
}

func (r *ApiOpenApiV30BrandMaWarningOrderListGetRequest) Execute() (*BrandMaWarningOrderListV30Response, *http.Response, error) {
	return r.ApiService.getExecute(r)
}

func (r *ApiOpenApiV30BrandMaWarningOrderListGetRequest) AccessToken(accessToken string) *ApiOpenApiV30BrandMaWarningOrderListGetRequest {
	r.ctx = context.WithValue(r.ctx, config.ContextAccessToken, accessToken)
	return r
}

func (r *ApiOpenApiV30BrandMaWarningOrderListGetRequest) WithLog(enable bool) *ApiOpenApiV30BrandMaWarningOrderListGetRequest {
	if enable {
		r.ctx = context.WithValue(r.ctx, config.ContextEnableLog, true)
	}
	return r
}

/*
OpenApiV30BrandMaWarningOrderListGet Method for OpenApiV30BrandMaWarningOrderListGet

查询账户预警信息

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@return ApiOpenApiV30BrandMaWarningOrderListGetRequest
*/
func (a *BrandMaWarningOrderListV30ApiService) Get(ctx context.Context) *ApiOpenApiV30BrandMaWarningOrderListGetRequest {
	return &ApiOpenApiV30BrandMaWarningOrderListGetRequest{
		ApiService: a,
		ctx:        ctx,
	}
}

// Execute executes the request
//
//	@return BrandMaWarningOrderListV30Response
func (a *BrandMaWarningOrderListV30ApiService) getExecute(r *ApiOpenApiV30BrandMaWarningOrderListGetRequest) (*BrandMaWarningOrderListV30Response, *http.Response, error) {
	var (
		localVarHTTPMethod  = http.MethodGet
		localVarPostBody    interface{}
		formFiles           map[string]*FormFileInfo
		localVarReturnValue *BrandMaWarningOrderListV30Response
	)

	r.ctx = a.client.prepareCtx(r.ctx)

	localBasePath := a.client.Cfg.GetBasePath()

	localVarPath := localBasePath + "/open_api/v3.0/brand/ma/warning_order/list/"

	localVarHeaderParams := make(map[string]string)
	formFiles = make(map[string]*FormFileInfo)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}
	if r.advertiserIds == nil {
		return localVarReturnValue, nil, ReportError("advertiserIds is required and must be specified")
	}

	parameterAddToHeaderOrQuery(localVarQueryParams, "advertiser_ids", r.advertiserIds)
	if r.startTime != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "start_time", r.startTime)
	}
	if r.endTime != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "end_time", r.endTime)
	}
	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.call(r.ctx, req, &localVarReturnValue)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}
	return localVarReturnValue, localVarHTTPResponse, nil
}
