/*
Oceanengine Open Api

巨量引擎开放平台 Open Api


*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"context"
	"net/http"
	"net/url"

	"github.com/oceanengine/ad_open_sdk_go/config"
	. "github.com/oceanengine/ad_open_sdk_go/models"
)

// ToolsClueRobotTaskCreateV2ApiService ToolsClueRobotTaskCreateV2Api service
type ToolsClueRobotTaskCreateV2ApiService service

type ApiOpenApi2ToolsClueRobotTaskCreatePostRequest struct {
	ctx                               context.Context
	ApiService                        *ToolsClueRobotTaskCreateV2ApiService
	toolsClueRobotTaskCreateV2Request *ToolsClueRobotTaskCreateV2Request
}

func (r *ApiOpenApi2ToolsClueRobotTaskCreatePostRequest) ToolsClueRobotTaskCreateV2Request(toolsClueRobotTaskCreateV2Request ToolsClueRobotTaskCreateV2Request) *ApiOpenApi2ToolsClueRobotTaskCreatePostRequest {
	r.toolsClueRobotTaskCreateV2Request = &toolsClueRobotTaskCreateV2Request
	return r
}

func (r *ApiOpenApi2ToolsClueRobotTaskCreatePostRequest) Execute() (*ToolsClueRobotTaskCreateV2Response, *http.Response, error) {
	return r.ApiService.postExecute(r)
}

func (r *ApiOpenApi2ToolsClueRobotTaskCreatePostRequest) AccessToken(accessToken string) *ApiOpenApi2ToolsClueRobotTaskCreatePostRequest {
	r.ctx = context.WithValue(r.ctx, config.ContextAccessToken, accessToken)
	return r
}

func (r *ApiOpenApi2ToolsClueRobotTaskCreatePostRequest) WithLog(enable bool) *ApiOpenApi2ToolsClueRobotTaskCreatePostRequest {
	if enable {
		r.ctx = context.WithValue(r.ctx, config.ContextEnableLog, true)
	}
	return r
}

/*
OpenApi2ToolsClueRobotTaskCreatePost Method for OpenApi2ToolsClueRobotTaskCreatePost

创建机器人任务。

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@return ApiOpenApi2ToolsClueRobotTaskCreatePostRequest
*/
func (a *ToolsClueRobotTaskCreateV2ApiService) Post(ctx context.Context) *ApiOpenApi2ToolsClueRobotTaskCreatePostRequest {
	return &ApiOpenApi2ToolsClueRobotTaskCreatePostRequest{
		ApiService: a,
		ctx:        ctx,
	}
}

// Execute executes the request
//
//	@return ToolsClueRobotTaskCreateV2Response
func (a *ToolsClueRobotTaskCreateV2ApiService) postExecute(r *ApiOpenApi2ToolsClueRobotTaskCreatePostRequest) (*ToolsClueRobotTaskCreateV2Response, *http.Response, error) {
	var (
		localVarHTTPMethod  = http.MethodPost
		localVarPostBody    interface{}
		formFiles           map[string]*FormFileInfo
		localVarReturnValue *ToolsClueRobotTaskCreateV2Response
	)

	r.ctx = a.client.prepareCtx(r.ctx)

	localBasePath := a.client.Cfg.GetBasePath()

	localVarPath := localBasePath + "/open_api/2/tools/clue/robot/task/create/"

	localVarHeaderParams := make(map[string]string)
	formFiles = make(map[string]*FormFileInfo)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{"application/json"}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// body params
	localVarPostBody = r.toolsClueRobotTaskCreateV2Request
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.call(r.ctx, req, &localVarReturnValue)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}
	return localVarReturnValue, localVarHTTPResponse, nil
}
