/*
Oceanengine Open Api

巨量引擎开放平台 Open Api


*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"context"
	"net/http"
	"net/url"

	"github.com/oceanengine/ad_open_sdk_go/config"
	. "github.com/oceanengine/ad_open_sdk_go/models"
)

// StarFeCommonServiceTalentDayJudgeCheckedInV2ApiService StarFeCommonServiceTalentDayJudgeCheckedInV2Api service
type StarFeCommonServiceTalentDayJudgeCheckedInV2ApiService service

type ApiOpenApi2StarFeCommonServiceTalentDayJudgeCheckedInGetRequest struct {
	ctx        context.Context
	ApiService *StarFeCommonServiceTalentDayJudgeCheckedInV2ApiService
	code       *string
}

// 二维码扫出来的内容
func (r *ApiOpenApi2StarFeCommonServiceTalentDayJudgeCheckedInGetRequest) Code(code string) *ApiOpenApi2StarFeCommonServiceTalentDayJudgeCheckedInGetRequest {
	r.code = &code
	return r
}

func (r *ApiOpenApi2StarFeCommonServiceTalentDayJudgeCheckedInGetRequest) Execute() (*StarFeCommonServiceTalentDayJudgeCheckedInV2Response, *http.Response, error) {
	return r.ApiService.getExecute(r)
}

func (r *ApiOpenApi2StarFeCommonServiceTalentDayJudgeCheckedInGetRequest) AccessToken(accessToken string) *ApiOpenApi2StarFeCommonServiceTalentDayJudgeCheckedInGetRequest {
	r.ctx = context.WithValue(r.ctx, config.ContextAccessToken, accessToken)
	return r
}

func (r *ApiOpenApi2StarFeCommonServiceTalentDayJudgeCheckedInGetRequest) WithLog(enable bool) *ApiOpenApi2StarFeCommonServiceTalentDayJudgeCheckedInGetRequest {
	if enable {
		r.ctx = context.WithValue(r.ctx, config.ContextEnableLog, true)
	}
	return r
}

/*
OpenApi2StarFeCommonServiceTalentDayJudgeCheckedInGet Method for OpenApi2StarFeCommonServiceTalentDayJudgeCheckedInGet

达人节签到查询用户信息

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@return ApiOpenApi2StarFeCommonServiceTalentDayJudgeCheckedInGetRequest
*/
func (a *StarFeCommonServiceTalentDayJudgeCheckedInV2ApiService) Get(ctx context.Context) *ApiOpenApi2StarFeCommonServiceTalentDayJudgeCheckedInGetRequest {
	return &ApiOpenApi2StarFeCommonServiceTalentDayJudgeCheckedInGetRequest{
		ApiService: a,
		ctx:        ctx,
	}
}

// Execute executes the request
//
//	@return StarFeCommonServiceTalentDayJudgeCheckedInV2Response
func (a *StarFeCommonServiceTalentDayJudgeCheckedInV2ApiService) getExecute(r *ApiOpenApi2StarFeCommonServiceTalentDayJudgeCheckedInGetRequest) (*StarFeCommonServiceTalentDayJudgeCheckedInV2Response, *http.Response, error) {
	var (
		localVarHTTPMethod  = http.MethodGet
		localVarPostBody    interface{}
		formFiles           map[string]*FormFileInfo
		localVarReturnValue *StarFeCommonServiceTalentDayJudgeCheckedInV2Response
	)

	r.ctx = a.client.prepareCtx(r.ctx)

	localBasePath := a.client.Cfg.GetBasePath()

	localVarPath := localBasePath + "/open_api/2/star/fe_common_service/talent_day/judge_checked_in/"

	localVarHeaderParams := make(map[string]string)
	formFiles = make(map[string]*FormFileInfo)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}
	if r.code == nil {
		return localVarReturnValue, nil, ReportError("code is required and must be specified")
	}

	parameterAddToHeaderOrQuery(localVarQueryParams, "code", r.code)
	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.call(r.ctx, req, &localVarReturnValue)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}
	return localVarReturnValue, localVarHTTPResponse, nil
}
