/*
Oceanengine Open Api

巨量引擎开放平台 Open Api


*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"context"
	"net/http"
	"net/url"

	"github.com/oceanengine/ad_open_sdk_go/config"
	. "github.com/oceanengine/ad_open_sdk_go/models"
)

// FileRebateDataProductCreateV2ApiService FileRebateDataProductCreateV2Api service
type FileRebateDataProductCreateV2ApiService service

type ApiOpenApi2FileRebateDataProductCreatePostRequest struct {
	ctx                                  context.Context
	ApiService                           *FileRebateDataProductCreateV2ApiService
	fileRebateDataProductCreateV2Request *FileRebateDataProductCreateV2Request
}

func (r *ApiOpenApi2FileRebateDataProductCreatePostRequest) FileRebateDataProductCreateV2Request(fileRebateDataProductCreateV2Request FileRebateDataProductCreateV2Request) *ApiOpenApi2FileRebateDataProductCreatePostRequest {
	r.fileRebateDataProductCreateV2Request = &fileRebateDataProductCreateV2Request
	return r
}

func (r *ApiOpenApi2FileRebateDataProductCreatePostRequest) Execute() (*FileRebateDataProductCreateV2Response, *http.Response, error) {
	return r.ApiService.postExecute(r)
}

func (r *ApiOpenApi2FileRebateDataProductCreatePostRequest) AccessToken(accessToken string) *ApiOpenApi2FileRebateDataProductCreatePostRequest {
	r.ctx = context.WithValue(r.ctx, config.ContextAccessToken, accessToken)
	return r
}

func (r *ApiOpenApi2FileRebateDataProductCreatePostRequest) WithLog(enable bool) *ApiOpenApi2FileRebateDataProductCreatePostRequest {
	if enable {
		r.ctx = context.WithValue(r.ctx, config.ContextEnableLog, true)
	}
	return r
}

/*
OpenApi2FileRebateDataProductCreatePost Method for OpenApi2FileRebateDataProductCreatePost

OpenAPI离线数据就绪消息，订阅及取消订阅

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@return ApiOpenApi2FileRebateDataProductCreatePostRequest
*/
func (a *FileRebateDataProductCreateV2ApiService) Post(ctx context.Context) *ApiOpenApi2FileRebateDataProductCreatePostRequest {
	return &ApiOpenApi2FileRebateDataProductCreatePostRequest{
		ApiService: a,
		ctx:        ctx,
	}
}

// Execute executes the request
//
//	@return FileRebateDataProductCreateV2Response
func (a *FileRebateDataProductCreateV2ApiService) postExecute(r *ApiOpenApi2FileRebateDataProductCreatePostRequest) (*FileRebateDataProductCreateV2Response, *http.Response, error) {
	var (
		localVarHTTPMethod  = http.MethodPost
		localVarPostBody    interface{}
		formFiles           map[string]*FormFileInfo
		localVarReturnValue *FileRebateDataProductCreateV2Response
	)

	r.ctx = a.client.prepareCtx(r.ctx)

	localBasePath := a.client.Cfg.GetBasePath()

	localVarPath := localBasePath + "/open_api/2/file/rebate/data_product/create/"

	localVarHeaderParams := make(map[string]string)
	formFiles = make(map[string]*FormFileInfo)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{"application/json"}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// body params
	localVarPostBody = r.fileRebateDataProductCreateV2Request
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.call(r.ctx, req, &localVarReturnValue)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}
	return localVarReturnValue, localVarHTTPResponse, nil
}
