/*
Oceanengine Open Api

巨量引擎开放平台 Open Api


*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package models

// SecurityScoreDisposalInfoGetV30DataDisposalInfoListDisposalStatus 处置状态
type SecurityScoreDisposalInfoGetV30DataDisposalInfoListDisposalStatus string

// List of security_score_disposal_info_get_v3.0_data_disposal_info_list_disposal_status
const (
	DISPOSAL_SecurityScoreDisposalInfoGetV30DataDisposalInfoListDisposalStatus SecurityScoreDisposalInfoGetV30DataDisposalInfoListDisposalStatus = "DISPOSAL"
)

// Ptr returns reference to security_score_disposal_info_get_v3.0_data_disposal_info_list_disposal_status value
func (v SecurityScoreDisposalInfoGetV30DataDisposalInfoListDisposalStatus) Ptr() *SecurityScoreDisposalInfoGetV30DataDisposalInfoListDisposalStatus {
	return &v
}
