/*
Oceanengine Open Api

巨量引擎开放平台 Open Api


*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package models

// QianchuanMaterialGetV10ResponseDataAdMaterialInfosInnerMaterialInfo 视频素材
type QianchuanMaterialGetV10ResponseDataAdMaterialInfosInnerMaterialInfo struct {
	ImageMaterial *QianchuanMaterialGetV10ResponseDataAdMaterialInfosInnerMaterialInfoImageMaterial `json:"image_material,omitempty"`
	MaterialType  QianchuanMaterialGetV10DataAdMaterialInfosMaterialInfoMaterialType                `json:"material_type"`
	RoomMaterial  *QianchuanMaterialGetV10ResponseDataAdMaterialInfosInnerMaterialInfoRoomMaterial  `json:"room_material,omitempty"`
	TitleMaterial *QianchuanMaterialGetV10ResponseDataAdMaterialInfosInnerMaterialInfoTitleMaterial `json:"title_material,omitempty"`
	VideoMaterial *QianchuanMaterialGetV10ResponseDataAdMaterialInfosInnerMaterialInfoVideoMaterial `json:"video_material,omitempty"`
}
