/*
Oceanengine Open Api

巨量引擎开放平台 Open Api


*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package models

// AdGetV2DataAudienceArticleCategory
type AdGetV2DataAudienceArticleCategory string

// List of ad_get_v2_data_audience_article_category
const (
	TRAVEL_AdGetV2DataAudienceArticleCategory        AdGetV2DataAudienceArticleCategory = "TRAVEL"
	TIPS_AdGetV2DataAudienceArticleCategory          AdGetV2DataAudienceArticleCategory = "TIPS"
	PHOTOGRAPHY_AdGetV2DataAudienceArticleCategory   AdGetV2DataAudienceArticleCategory = "PHOTOGRAPHY"
	LOCAL_AdGetV2DataAudienceArticleCategory         AdGetV2DataAudienceArticleCategory = "LOCAL"
	COMICS_AdGetV2DataAudienceArticleCategory        AdGetV2DataAudienceArticleCategory = "COMICS"
	MOVIE_AdGetV2DataAudienceArticleCategory         AdGetV2DataAudienceArticleCategory = "MOVIE"
	GAMES_AdGetV2DataAudienceArticleCategory         AdGetV2DataAudienceArticleCategory = "GAMES"
	PARENTING_AdGetV2DataAudienceArticleCategory     AdGetV2DataAudienceArticleCategory = "PARENTING"
	REGIMEN_AdGetV2DataAudienceArticleCategory       AdGetV2DataAudienceArticleCategory = "REGIMEN"
	WORKPLACE_AdGetV2DataAudienceArticleCategory     AdGetV2DataAudienceArticleCategory = "WORKPLACE"
	MILITARY_AdGetV2DataAudienceArticleCategory      AdGetV2DataAudienceArticleCategory = "MILITARY"
	GOVERNMENT_AdGetV2DataAudienceArticleCategory    AdGetV2DataAudienceArticleCategory = "GOVERNMENT"
	TECHNOLOGY_AdGetV2DataAudienceArticleCategory    AdGetV2DataAudienceArticleCategory = "TECHNOLOGY"
	LAWS_AdGetV2DataAudienceArticleCategory          AdGetV2DataAudienceArticleCategory = "LAWS"
	ESTATE_AdGetV2DataAudienceArticleCategory        AdGetV2DataAudienceArticleCategory = "ESTATE"
	SCIENCE_AdGetV2DataAudienceArticleCategory       AdGetV2DataAudienceArticleCategory = "SCIENCE"
	CARS_AdGetV2DataAudienceArticleCategory          AdGetV2DataAudienceArticleCategory = "CARS"
	DESIGN_AdGetV2DataAudienceArticleCategory        AdGetV2DataAudienceArticleCategory = "DESIGN"
	HEALTH_AdGetV2DataAudienceArticleCategory        AdGetV2DataAudienceArticleCategory = "HEALTH"
	EDUCATION_AdGetV2DataAudienceArticleCategory     AdGetV2DataAudienceArticleCategory = "EDUCATION"
	CONSTELLATION_AdGetV2DataAudienceArticleCategory AdGetV2DataAudienceArticleCategory = "CONSTELLATION"
	RUMOR_CRACKER_AdGetV2DataAudienceArticleCategory AdGetV2DataAudienceArticleCategory = "RUMOR_CRACKER"
	INTERNATIONAL_AdGetV2DataAudienceArticleCategory AdGetV2DataAudienceArticleCategory = "INTERNATIONAL"
	STORIES_AdGetV2DataAudienceArticleCategory       AdGetV2DataAudienceArticleCategory = "STORIES"
	EXPLORE_AdGetV2DataAudienceArticleCategory       AdGetV2DataAudienceArticleCategory = "EXPLORE"
	EMOTION_AdGetV2DataAudienceArticleCategory       AdGetV2DataAudienceArticleCategory = "EMOTION"
	WEIGHT_LOSING_AdGetV2DataAudienceArticleCategory AdGetV2DataAudienceArticleCategory = "WEIGHT_LOSING"
	HOME_AdGetV2DataAudienceArticleCategory          AdGetV2DataAudienceArticleCategory = "HOME"
	COLLECTION_AdGetV2DataAudienceArticleCategory    AdGetV2DataAudienceArticleCategory = "COLLECTION"
	AMUSEMENT_AdGetV2DataAudienceArticleCategory     AdGetV2DataAudienceArticleCategory = "AMUSEMENT"
	CULTURE_AdGetV2DataAudienceArticleCategory       AdGetV2DataAudienceArticleCategory = "CULTURE"
	BUSINESS_AdGetV2DataAudienceArticleCategory      AdGetV2DataAudienceArticleCategory = "BUSINESS"
	SOCIETY_AdGetV2DataAudienceArticleCategory       AdGetV2DataAudienceArticleCategory = "SOCIETY"
	GRADUATES_AdGetV2DataAudienceArticleCategory     AdGetV2DataAudienceArticleCategory = "GRADUATES"
	HISTORY_AdGetV2DataAudienceArticleCategory       AdGetV2DataAudienceArticleCategory = "HISTORY"
	GOURMET_AdGetV2DataAudienceArticleCategory       AdGetV2DataAudienceArticleCategory = "GOURMET"
	FREAK_AdGetV2DataAudienceArticleCategory         AdGetV2DataAudienceArticleCategory = "FREAK"
	ANIMATION_AdGetV2DataAudienceArticleCategory     AdGetV2DataAudienceArticleCategory = "ANIMATION"
	FASHION_AdGetV2DataAudienceArticleCategory       AdGetV2DataAudienceArticleCategory = "FASHION"
	PETS_AdGetV2DataAudienceArticleCategory          AdGetV2DataAudienceArticleCategory = "PETS"
	ENTERTAINMENT_AdGetV2DataAudienceArticleCategory AdGetV2DataAudienceArticleCategory = "ENTERTAINMENT"
	ESSAY_AdGetV2DataAudienceArticleCategory         AdGetV2DataAudienceArticleCategory = "ESSAY"
	DIGITAL_AdGetV2DataAudienceArticleCategory       AdGetV2DataAudienceArticleCategory = "DIGITAL"
	SPORTS_AdGetV2DataAudienceArticleCategory        AdGetV2DataAudienceArticleCategory = "SPORTS"
	FINANCE_AdGetV2DataAudienceArticleCategory       AdGetV2DataAudienceArticleCategory = "FINANCE"
)

// Ptr returns reference to ad_get_v2_data_audience_article_category value
func (v AdGetV2DataAudienceArticleCategory) Ptr() *AdGetV2DataAudienceArticleCategory {
	return &v
}
