/*
Oceanengine Open Api

巨量引擎开放平台 Open Api


*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package models

// ReportCampaignGetV2FilteringInventoryTypes
type ReportCampaignGetV2FilteringInventoryTypes string

// List of report_campaign_get_v2_filtering_inventory_types
const (
	INVENTORY_VIDEO_FEED_ReportCampaignGetV2FilteringInventoryTypes   ReportCampaignGetV2FilteringInventoryTypes = "INVENTORY_VIDEO_FEED"
	INVENTORY_UNION_SLOT_ReportCampaignGetV2FilteringInventoryTypes   ReportCampaignGetV2FilteringInventoryTypes = "INVENTORY_UNION_SLOT"
	INVENTORY_HOTSOON_FEED_ReportCampaignGetV2FilteringInventoryTypes ReportCampaignGetV2FilteringInventoryTypes = "INVENTORY_HOTSOON_FEED"
	INVENTORY_AUTOMOBILE_ReportCampaignGetV2FilteringInventoryTypes   ReportCampaignGetV2FilteringInventoryTypes = "INVENTORY_AUTOMOBILE"
	INVENTORY_PIPIXIA_ReportCampaignGetV2FilteringInventoryTypes      ReportCampaignGetV2FilteringInventoryTypes = "INVENTORY_PIPIXIA"
	INVENTORY_BEAUTY_ReportCampaignGetV2FilteringInventoryTypes       ReportCampaignGetV2FilteringInventoryTypes = "INVENTORY_BEAUTY"
	INVENTORY_FURNISH_ReportCampaignGetV2FilteringInventoryTypes      ReportCampaignGetV2FilteringInventoryTypes = "INVENTORY_FURNISH"
	INVENTORY_STUDY_ReportCampaignGetV2FilteringInventoryTypes        ReportCampaignGetV2FilteringInventoryTypes = "INVENTORY_STUDY"
	INVENTORY_SEARCH_ReportCampaignGetV2FilteringInventoryTypes       ReportCampaignGetV2FilteringInventoryTypes = "INVENTORY_SEARCH"
	INVENTORY_FEED_ReportCampaignGetV2FilteringInventoryTypes         ReportCampaignGetV2FilteringInventoryTypes = "INVENTORY_FEED"
	INVENTORY_AWEME_FEED_ReportCampaignGetV2FilteringInventoryTypes   ReportCampaignGetV2FilteringInventoryTypes = "INVENTORY_AWEME_FEED"
	INVENTORY_UNIVERSAL_ReportCampaignGetV2FilteringInventoryTypes    ReportCampaignGetV2FilteringInventoryTypes = "INVENTORY_UNIVERSAL"
	INVENTORY_TOMATO_NOVEL_ReportCampaignGetV2FilteringInventoryTypes ReportCampaignGetV2FilteringInventoryTypes = "INVENTORY_TOMATO_NOVEL"
	UNION_BOUTIQUE_GAME_ReportCampaignGetV2FilteringInventoryTypes    ReportCampaignGetV2FilteringInventoryTypes = "UNION_BOUTIQUE_GAME"
	INVENTORY_FACE_U_ReportCampaignGetV2FilteringInventoryTypes       ReportCampaignGetV2FilteringInventoryTypes = "INVENTORY_FACE_U"
)

// Ptr returns reference to report_campaign_get_v2_filtering_inventory_types value
func (v ReportCampaignGetV2FilteringInventoryTypes) Ptr() *ReportCampaignGetV2FilteringInventoryTypes {
	return &v
}
