/*
Oceanengine Open Api

巨量引擎开放平台 Open Api


*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package models

// SecurityScoreDisposalInfoGetV30Filtering
type SecurityScoreDisposalInfoGetV30Filtering struct {
	DisposalAction *SecurityScoreDisposalInfoGetV30FilteringDisposalAction `json:"disposal_action,omitempty"`
	DisposalStatus *SecurityScoreDisposalInfoGetV30FilteringDisposalStatus `json:"disposal_status,omitempty"`
}
