/*
Oceanengine Open Api

巨量引擎开放平台 Open Api


*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package models

// EventManagerOptimizedGoalGetV2V30AppType
type EventManagerOptimizedGoalGetV2V30AppType string

// List of event_manager_optimized_goal_get_v2_v3.0_app_type
const (
	ANDROID_EventManagerOptimizedGoalGetV2V30AppType EventManagerOptimizedGoalGetV2V30AppType = "ANDROID"
	DEFAULT_EventManagerOptimizedGoalGetV2V30AppType EventManagerOptimizedGoalGetV2V30AppType = "DEFAULT"
	HARMONY_EventManagerOptimizedGoalGetV2V30AppType EventManagerOptimizedGoalGetV2V30AppType = "HARMONY"
	IOS_EventManagerOptimizedGoalGetV2V30AppType     EventManagerOptimizedGoalGetV2V30AppType = "IOS"
)

// Ptr returns reference to event_manager_optimized_goal_get_v2_v3.0_app_type value
func (v EventManagerOptimizedGoalGetV2V30AppType) Ptr() *EventManagerOptimizedGoalGetV2V30AppType {
	return &v
}
