/*
Oceanengine Open Api

巨量引擎开放平台 Open Api


*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package models

// BrandMaterialCreateV30ContentType 投放内容
type BrandMaterialCreateV30ContentType string

// List of brand_material_create_v3.0_content_type
const (
	LANDING_PAGE_BrandMaterialCreateV30ContentType BrandMaterialCreateV30ContentType = "LANDING_PAGE"
	NATIVE_BrandMaterialCreateV30ContentType       BrandMaterialCreateV30ContentType = "NATIVE"
)

// Ptr returns reference to brand_material_create_v3.0_content_type value
func (v BrandMaterialCreateV30ContentType) Ptr() *BrandMaterialCreateV30ContentType {
	return &v
}
