/*
Oceanengine Open Api

巨量引擎开放平台 Open Api


*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package models

// ToolsJointBidCreateV30JointScopeInfoShopScopeDimension
type ToolsJointBidCreateV30JointScopeInfoShopScopeDimension string

// List of tools_joint_bid_create_v3.0_joint_scope_info_shop_scope_dimension
const (
	ADVERTISER_ID_ToolsJointBidCreateV30JointScopeInfoShopScopeDimension ToolsJointBidCreateV30JointScopeInfoShopScopeDimension = "ADVERTISER_ID"
	CUSTOMER_ID_ToolsJointBidCreateV30JointScopeInfoShopScopeDimension   ToolsJointBidCreateV30JointScopeInfoShopScopeDimension = "CUSTOMER_ID"
)

// Ptr returns reference to tools_joint_bid_create_v3.0_joint_scope_info_shop_scope_dimension value
func (v ToolsJointBidCreateV30JointScopeInfoShopScopeDimension) Ptr() *ToolsJointBidCreateV30JointScopeInfoShopScopeDimension {
	return &v
}
