/*
Oceanengine Open Api

巨量引擎开放平台 Open Api


*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package models

// AdvertiserInfoV2DataRole
type AdvertiserInfoV2DataRole string

// List of advertiser_info_v2_data_role
const (
	ROLE_AWEME_PROMOTION_ADVERTISER_AdvertiserInfoV2DataRole     AdvertiserInfoV2DataRole = "ROLE_AWEME_PROMOTION_ADVERTISER"
	ROLE_ECP_INTERNAL_ADVERTISER_AdvertiserInfoV2DataRole        AdvertiserInfoV2DataRole = "ROLE_ECP_INTERNAL_ADVERTISER"
	ROLE_AGENT_AdvertiserInfoV2DataRole                          AdvertiserInfoV2DataRole = "ROLE_AGENT"
	ROLE_DSP_ADVERTISER_AdvertiserInfoV2DataRole                 AdvertiserInfoV2DataRole = "ROLE_DSP_ADVERTISER"
	ROLE_ECP_CHILD_ADVERTISER_AdvertiserInfoV2DataRole           AdvertiserInfoV2DataRole = "ROLE_ECP_CHILD_ADVERTISER"
	ROLE_ECP_ADVERTISER_AdvertiserInfoV2DataRole                 AdvertiserInfoV2DataRole = "ROLE_ECP_ADVERTISER"
	ROLE_ADVERTISER_AdvertiserInfoV2DataRole                     AdvertiserInfoV2DataRole = "ROLE_ADVERTISER"
	ROLE_ADVERTISER_SYSTEM_ACCOUNT_AdvertiserInfoV2DataRole      AdvertiserInfoV2DataRole = "ROLE_ADVERTISER_SYSTEM_ACCOUNT"
	ROLE_AGENT_SYSTEM_ACCOUNT_AdvertiserInfoV2DataRole           AdvertiserInfoV2DataRole = "ROLE_AGENT_SYSTEM_ACCOUNT"
	ROLE_LOCAL_LIFE_VIRTUAL_ADVERTISER_AdvertiserInfoV2DataRole  AdvertiserInfoV2DataRole = "ROLE_LOCAL_LIFE_VIRTUAL_ADVERTISER"
	ROLE_HOTSOON_ADVERTISER_AdvertiserInfoV2DataRole             AdvertiserInfoV2DataRole = "ROLE_HOTSOON_ADVERTISER"
	ROLE_LITE_ADVERTISER_AdvertiserInfoV2DataRole                AdvertiserInfoV2DataRole = "ROLE_LITE_ADVERTISER"
	ROLE_CHILD_AGENT_AdvertiserInfoV2DataRole                    AdvertiserInfoV2DataRole = "ROLE_CHILD_AGENT"
	ROLE_CHILD_ADVERTISER_AdvertiserInfoV2DataRole               AdvertiserInfoV2DataRole = "ROLE_CHILD_ADVERTISER"
	ROLE_LOCAL_LIFE_ADVERTISER_AdvertiserInfoV2DataRole          AdvertiserInfoV2DataRole = "ROLE_LOCAL_LIFE_ADVERTISER"
	ROLE_DOUDIAN_ADVERTISER_AdvertiserInfoV2DataRole             AdvertiserInfoV2DataRole = "ROLE_DOUDIAN_ADVERTISER"
	ROLE_AGENT_ABSTRACT_AdvertiserInfoV2DataRole                 AdvertiserInfoV2DataRole = "ROLE_AGENT_ABSTRACT"
	ROLE_LOCAL_LIFE_INTERNAL_ADVERTISER_AdvertiserInfoV2DataRole AdvertiserInfoV2DataRole = "ROLE_LOCAL_LIFE_INTERNAL_ADVERTISER"
	ROLE_HOTSOON_PROMOTION_ADVERTISER_AdvertiserInfoV2DataRole   AdvertiserInfoV2DataRole = "ROLE_HOTSOON_PROMOTION_ADVERTISER"
	ROLE_MAJORDOMO_AdvertiserInfoV2DataRole                      AdvertiserInfoV2DataRole = "ROLE_MAJORDOMO"
	ROLE_ADVERTISER_ABSTRACT_AdvertiserInfoV2DataRole            AdvertiserInfoV2DataRole = "ROLE_ADVERTISER_ABSTRACT"
	ROLE_INTERNAL_ADV_AdvertiserInfoV2DataRole                   AdvertiserInfoV2DataRole = "ROLE_INTERNAL_ADV"
	ROLE_ADMIN_AdvertiserInfoV2DataRole                          AdvertiserInfoV2DataRole = "ROLE_ADMIN"
	ROLE_PGC_ADVERTISER_AdvertiserInfoV2DataRole                 AdvertiserInfoV2DataRole = "ROLE_PGC_ADVERTISER"
)

// Ptr returns reference to advertiser_info_v2_data_role value
func (v AdvertiserInfoV2DataRole) Ptr() *AdvertiserInfoV2DataRole {
	return &v
}
