/*
Oceanengine Open Api

巨量引擎开放平台 Open Api


*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package models

// AdvertiserDeliveryQualificationListV30QualificationType
type AdvertiserDeliveryQualificationListV30QualificationType string

// List of advertiser_delivery_qualification_list_v3.0_qualification_type
const (
	AGENT_ARRANGEMENT_AdvertiserDeliveryQualificationListV30QualificationType                           AdvertiserDeliveryQualificationListV30QualificationType = "AGENT_ARRANGEMENT"
	AUTHORIZATION_CONTRACT_AdvertiserDeliveryQualificationListV30QualificationType                      AdvertiserDeliveryQualificationListV30QualificationType = "AUTHORIZATION_CONTRACT"
	DISTRIBUTION_AUTHORIZATION_AdvertiserDeliveryQualificationListV30QualificationType                  AdvertiserDeliveryQualificationListV30QualificationType = "DISTRIBUTION_AUTHORIZATION"
	FOOD_BUSINESS_LICENSE_AdvertiserDeliveryQualificationListV30QualificationType                       AdvertiserDeliveryQualificationListV30QualificationType = "FOOD_BUSINESS_LICENSE"
	ICP_RECORD_AUTHORIZATION_AdvertiserDeliveryQualificationListV30QualificationType                    AdvertiserDeliveryQualificationListV30QualificationType = "ICP_RECORD_AUTHORIZATION"
	OTHER_CERTIFICATION_AdvertiserDeliveryQualificationListV30QualificationType                         AdvertiserDeliveryQualificationListV30QualificationType = "OTHER_CERTIFICATION"
	PATENT_CERTIFICATE_AdvertiserDeliveryQualificationListV30QualificationType                          AdvertiserDeliveryQualificationListV30QualificationType = "PATENT_CERTIFICATE"
	PORTRAIT_AUTHORIZATION_AdvertiserDeliveryQualificationListV30QualificationType                      AdvertiserDeliveryQualificationListV30QualificationType = "PORTRAIT_AUTHORIZATION"
	QUALITY_REPORT_AdvertiserDeliveryQualificationListV30QualificationType                              AdvertiserDeliveryQualificationListV30QualificationType = "QUALITY_REPORT"
	SOFTWARE_COPYRIGHT_REGISTRATION_CERTIFICATE_AdvertiserDeliveryQualificationListV30QualificationType AdvertiserDeliveryQualificationListV30QualificationType = "SOFTWARE_COPYRIGHT_REGISTRATION_CERTIFICATE"
	TRADEMARK_REGISTRATION_CERTIFICATE_AdvertiserDeliveryQualificationListV30QualificationType          AdvertiserDeliveryQualificationListV30QualificationType = "TRADEMARK_REGISTRATION_CERTIFICATE"
	VIDEO_MATERIAL_PRODUCTION_IP_AUTHORIZATION_AdvertiserDeliveryQualificationListV30QualificationType  AdvertiserDeliveryQualificationListV30QualificationType = "VIDEO_MATERIAL_PRODUCTION_IP_AUTHORIZATION"
)

// Ptr returns reference to advertiser_delivery_qualification_list_v3.0_qualification_type value
func (v AdvertiserDeliveryQualificationListV30QualificationType) Ptr() *AdvertiserDeliveryQualificationListV30QualificationType {
	return &v
}
