/*
Oceanengine Open Api

巨量引擎开放平台 Open Api


*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package models

// LocalProjectCreateV30BudgetMode 预算模式设置 本地交易场景下设置说明： 交易下仅支持日预算
type LocalProjectCreateV30BudgetMode string

// List of local_project_create_v3.0_budget_mode
const (
	ALL_LocalProjectCreateV30BudgetMode               LocalProjectCreateV30BudgetMode = "ALL"
	BUDGET_MODE_DAY_LocalProjectCreateV30BudgetMode   LocalProjectCreateV30BudgetMode = "BUDGET_MODE_DAY"
	BUDGET_MODE_TOTAL_LocalProjectCreateV30BudgetMode LocalProjectCreateV30BudgetMode = "BUDGET_MODE_TOTAL"
)

// Ptr returns reference to local_project_create_v3.0_budget_mode value
func (v LocalProjectCreateV30BudgetMode) Ptr() *LocalProjectCreateV30BudgetMode {
	return &v
}
