/*
Oceanengine Open Api

巨量引擎开放平台 Open Api


*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package models

// AudiencePackageUpdateV2Platform
type AudiencePackageUpdateV2Platform string

// List of audience_package_update_v2_platform
const (
	PC_AudiencePackageUpdateV2Platform      AudiencePackageUpdateV2Platform = "PC"
	IOS_AudiencePackageUpdateV2Platform     AudiencePackageUpdateV2Platform = "IOS"
	IPAD_AudiencePackageUpdateV2Platform    AudiencePackageUpdateV2Platform = "IPAD"
	HARMONY_AudiencePackageUpdateV2Platform AudiencePackageUpdateV2Platform = "HARMONY"
	WAP_AudiencePackageUpdateV2Platform     AudiencePackageUpdateV2Platform = "WAP"
	ANDROID_AudiencePackageUpdateV2Platform AudiencePackageUpdateV2Platform = "ANDROID"
)

// Ptr returns reference to audience_package_update_v2_platform value
func (v AudiencePackageUpdateV2Platform) Ptr() *AudiencePackageUpdateV2Platform {
	return &v
}
