/*
Oceanengine Open Api

巨量引擎开放平台 Open Api

API version: 1.1.12
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package models

// ToolsStarTaskTitleTopicGetV2ResponseData
type ToolsStarTaskTitleTopicGetV2ResponseData struct {
	//
	Topics []*ToolsStarTaskTitleTopicGetV2ResponseDataTopicsInner `json:"topics,omitempty"`
}
