/*
Oceanengine Open Api

巨量引擎开放平台 Open Api

API version: 1.0.18
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package models

import (
	"fmt"
)

// ToolsMicroAppUpdateV30AppPageOperateType
type ToolsMicroAppUpdateV30AppPageOperateType string

// List of tools_micro_app_update_v3.0_app_page_operate_type
const (
	NEW_ToolsMicroAppUpdateV30AppPageOperateType    ToolsMicroAppUpdateV30AppPageOperateType = "NEW"
	MODIFY_ToolsMicroAppUpdateV30AppPageOperateType ToolsMicroAppUpdateV30AppPageOperateType = "MODIFY"
	DELETE_ToolsMicroAppUpdateV30AppPageOperateType ToolsMicroAppUpdateV30AppPageOperateType = "DELETE"
)

// All allowed values of ToolsMicroAppUpdateV30AppPageOperateType enum
var AllowedToolsMicroAppUpdateV30AppPageOperateTypeEnumValues = []ToolsMicroAppUpdateV30AppPageOperateType{
	"NEW",
	"MODIFY",
	"DELETE",
}

// NewToolsMicroAppUpdateV30AppPageOperateTypeFromValue returns a pointer to a valid ToolsMicroAppUpdateV30AppPageOperateType
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewToolsMicroAppUpdateV30AppPageOperateTypeFromValue(v string) (*ToolsMicroAppUpdateV30AppPageOperateType, error) {
	ev := ToolsMicroAppUpdateV30AppPageOperateType(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for ToolsMicroAppUpdateV30AppPageOperateType: valid values are %v", v, AllowedToolsMicroAppUpdateV30AppPageOperateTypeEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v ToolsMicroAppUpdateV30AppPageOperateType) IsValid() bool {
	for _, existing := range AllowedToolsMicroAppUpdateV30AppPageOperateTypeEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to tools_micro_app_update_v3.0_app_page_operate_type value
func (v ToolsMicroAppUpdateV30AppPageOperateType) Ptr() *ToolsMicroAppUpdateV30AppPageOperateType {
	return &v
}
