/*
Oceanengine Open Api

巨量引擎开放平台 Open Api


*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package models

// StarDemandOmCreateChallengeV2ChallengeInfoProviderScope
type StarDemandOmCreateChallengeV2ChallengeInfoProviderScope int64

// List of star_demand_om_create_challenge_v2_challenge_info_provider_scope
const (
	Enum_1_StarDemandOmCreateChallengeV2ChallengeInfoProviderScope StarDemandOmCreateChallengeV2ChallengeInfoProviderScope = 1
	Enum_2_StarDemandOmCreateChallengeV2ChallengeInfoProviderScope StarDemandOmCreateChallengeV2ChallengeInfoProviderScope = 2
)

// Ptr returns reference to star_demand_om_create_challenge_v2_challenge_info_provider_scope value
func (v StarDemandOmCreateChallengeV2ChallengeInfoProviderScope) Ptr() *StarDemandOmCreateChallengeV2ChallengeInfoProviderScope {
	return &v
}
