/*
Oceanengine Open Api

巨量引擎开放平台 Open Api


*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package models

// ProjectListV30DataListAudienceAwemeFanBehaviors
type ProjectListV30DataListAudienceAwemeFanBehaviors string

// List of project_list_v3.0_data_list_audience_aweme_fan_behaviors
const (
	COMMENTED_USER_ProjectListV30DataListAudienceAwemeFanBehaviors       ProjectListV30DataListAudienceAwemeFanBehaviors = "COMMENTED_USER"
	FOLLOWED_USER_ProjectListV30DataListAudienceAwemeFanBehaviors        ProjectListV30DataListAudienceAwemeFanBehaviors = "FOLLOWED_USER"
	GOODS_CARTS_CLICK_ProjectListV30DataListAudienceAwemeFanBehaviors    ProjectListV30DataListAudienceAwemeFanBehaviors = "GOODS_CARTS_CLICK"
	GOODS_CARTS_ORDER_ProjectListV30DataListAudienceAwemeFanBehaviors    ProjectListV30DataListAudienceAwemeFanBehaviors = "GOODS_CARTS_ORDER"
	LIKED_USER_ProjectListV30DataListAudienceAwemeFanBehaviors           ProjectListV30DataListAudienceAwemeFanBehaviors = "LIKED_USER"
	LIVE_COMMENT_ProjectListV30DataListAudienceAwemeFanBehaviors         ProjectListV30DataListAudienceAwemeFanBehaviors = "LIVE_COMMENT"
	LIVE_EFFECTIVE_WATCH_ProjectListV30DataListAudienceAwemeFanBehaviors ProjectListV30DataListAudienceAwemeFanBehaviors = "LIVE_EFFECTIVE_WATCH"
	LIVE_EXCEPTIONAL_ProjectListV30DataListAudienceAwemeFanBehaviors     ProjectListV30DataListAudienceAwemeFanBehaviors = "LIVE_EXCEPTIONAL"
	LIVE_GOODS_CLICK_ProjectListV30DataListAudienceAwemeFanBehaviors     ProjectListV30DataListAudienceAwemeFanBehaviors = "LIVE_GOODS_CLICK"
	LIVE_GOODS_ORDER_ProjectListV30DataListAudienceAwemeFanBehaviors     ProjectListV30DataListAudienceAwemeFanBehaviors = "LIVE_GOODS_ORDER"
	LIVE_WATCH_ProjectListV30DataListAudienceAwemeFanBehaviors           ProjectListV30DataListAudienceAwemeFanBehaviors = "LIVE_WATCH"
	SHARED_USER_ProjectListV30DataListAudienceAwemeFanBehaviors          ProjectListV30DataListAudienceAwemeFanBehaviors = "SHARED_USER"
)

// Ptr returns reference to project_list_v3.0_data_list_audience_aweme_fan_behaviors value
func (v ProjectListV30DataListAudienceAwemeFanBehaviors) Ptr() *ProjectListV30DataListAudienceAwemeFanBehaviors {
	return &v
}
