/*
Oceanengine Open Api

巨量引擎开放平台 Open Api


*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package models

// ToolsAppManagementBookingRecordsGetV2HostType
type ToolsAppManagementBookingRecordsGetV2HostType string

// List of tools_app_management_booking_records_get_v2_host_type
const (
	HOST_IN_ToolsAppManagementBookingRecordsGetV2HostType  ToolsAppManagementBookingRecordsGetV2HostType = "HOST_IN"
	HOST_OUT_ToolsAppManagementBookingRecordsGetV2HostType ToolsAppManagementBookingRecordsGetV2HostType = "HOST_OUT"
)

// Ptr returns reference to tools_app_management_booking_records_get_v2_host_type value
func (v ToolsAppManagementBookingRecordsGetV2HostType) Ptr() *ToolsAppManagementBookingRecordsGetV2HostType {
	return &v
}
