/*
Oceanengine Open Api

巨量引擎开放平台 Open Api


*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package models

// ToolsMicroAppUpdateV30RevenueModel
type ToolsMicroAppUpdateV30RevenueModel string

// List of tools_micro_app_update_v3.0_revenue_model
const (
	IAA_ToolsMicroAppUpdateV30RevenueModel  ToolsMicroAppUpdateV30RevenueModel = "IAA"
	IAAP_ToolsMicroAppUpdateV30RevenueModel ToolsMicroAppUpdateV30RevenueModel = "IAAP"
	IAP_ToolsMicroAppUpdateV30RevenueModel  ToolsMicroAppUpdateV30RevenueModel = "IAP"
)

// Ptr returns reference to tools_micro_app_update_v3.0_revenue_model value
func (v ToolsMicroAppUpdateV30RevenueModel) Ptr() *ToolsMicroAppUpdateV30RevenueModel {
	return &v
}
