/*
Oceanengine Open Api

巨量引擎开放平台 Open Api

API version: 1.1.2
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package models

// StarChallengeAuthorListV2ResponseDataPageInfo
type StarChallengeAuthorListV2ResponseDataPageInfo struct {
	//
	Limit int64 `json:"limit"`
	//
	Page int64 `json:"page"`
	//
	TotalCount int64 `json:"total_count"`
}
