/*
Oceanengine Open Api

巨量引擎开放平台 Open Api


*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package models

// ProjectCreateV30DeliveryRangeInventoryType
type ProjectCreateV30DeliveryRangeInventoryType string

// List of project_create_v3.0_delivery_range_inventory_type
const (
	INVENTORY_AWEME_FEED_ProjectCreateV30DeliveryRangeInventoryType      ProjectCreateV30DeliveryRangeInventoryType = "INVENTORY_AWEME_FEED"
	INVENTORY_FEED_ProjectCreateV30DeliveryRangeInventoryType            ProjectCreateV30DeliveryRangeInventoryType = "INVENTORY_FEED"
	INVENTORY_HOMED_AGGREGATE_ProjectCreateV30DeliveryRangeInventoryType ProjectCreateV30DeliveryRangeInventoryType = "INVENTORY_HOMED_AGGREGATE"
	INVENTORY_HOTSOON_FEED_ProjectCreateV30DeliveryRangeInventoryType    ProjectCreateV30DeliveryRangeInventoryType = "INVENTORY_HOTSOON_FEED"
	INVENTORY_SEARCH_ProjectCreateV30DeliveryRangeInventoryType          ProjectCreateV30DeliveryRangeInventoryType = "INVENTORY_SEARCH"
	INVENTORY_TOMATO_NOVEL_ProjectCreateV30DeliveryRangeInventoryType    ProjectCreateV30DeliveryRangeInventoryType = "INVENTORY_TOMATO_NOVEL"
	INVENTORY_UNION_SLOT_ProjectCreateV30DeliveryRangeInventoryType      ProjectCreateV30DeliveryRangeInventoryType = "INVENTORY_UNION_SLOT"
	INVENTORY_VIDEO_FEED_ProjectCreateV30DeliveryRangeInventoryType      ProjectCreateV30DeliveryRangeInventoryType = "INVENTORY_VIDEO_FEED"
	UNION_BOUTIQUE_GAME_ProjectCreateV30DeliveryRangeInventoryType       ProjectCreateV30DeliveryRangeInventoryType = "UNION_BOUTIQUE_GAME"
)

// Ptr returns reference to project_create_v3.0_delivery_range_inventory_type value
func (v ProjectCreateV30DeliveryRangeInventoryType) Ptr() *ProjectCreateV30DeliveryRangeInventoryType {
	return &v
}
