/*
Oceanengine Open Api

巨量引擎开放平台 Open Api


*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package models

// EventManagerDeepBidTypeGetV30LandingType
type EventManagerDeepBidTypeGetV30LandingType string

// List of event_manager_deep_bid_type_get_v3.0_landing_type
const (
	APP_EventManagerDeepBidTypeGetV30LandingType            EventManagerDeepBidTypeGetV30LandingType = "APP"
	ARTICLE_EventManagerDeepBidTypeGetV30LandingType        EventManagerDeepBidTypeGetV30LandingType = "ARTICLE"
	BRAND_EXTERNAL_EventManagerDeepBidTypeGetV30LandingType EventManagerDeepBidTypeGetV30LandingType = "BRAND_EXTERNAL"
	DPA_EventManagerDeepBidTypeGetV30LandingType            EventManagerDeepBidTypeGetV30LandingType = "DPA"
	GOODS_EventManagerDeepBidTypeGetV30LandingType          EventManagerDeepBidTypeGetV30LandingType = "GOODS"
	LINK_EventManagerDeepBidTypeGetV30LandingType           EventManagerDeepBidTypeGetV30LandingType = "LINK"
	LIVE_EventManagerDeepBidTypeGetV30LandingType           EventManagerDeepBidTypeGetV30LandingType = "LIVE"
	MICRO_GAME_EventManagerDeepBidTypeGetV30LandingType     EventManagerDeepBidTypeGetV30LandingType = "MICRO_GAME"
	NATIVE_ACTION_EventManagerDeepBidTypeGetV30LandingType  EventManagerDeepBidTypeGetV30LandingType = "NATIVE_ACTION"
	QUICK_APP_EventManagerDeepBidTypeGetV30LandingType      EventManagerDeepBidTypeGetV30LandingType = "QUICK_APP"
	SHOP_EventManagerDeepBidTypeGetV30LandingType           EventManagerDeepBidTypeGetV30LandingType = "SHOP"
	STORE_EventManagerDeepBidTypeGetV30LandingType          EventManagerDeepBidTypeGetV30LandingType = "STORE"
)

// Ptr returns reference to event_manager_deep_bid_type_get_v3.0_landing_type value
func (v EventManagerDeepBidTypeGetV30LandingType) Ptr() *EventManagerDeepBidTypeGetV30LandingType {
	return &v
}
