/*
Oceanengine Open Api

巨量引擎开放平台 Open Api


*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package models

// ToolsAppManagementExtendPackageCreateV2V2ResponseData
type ToolsAppManagementExtendPackageCreateV2V2ResponseData struct {
	// 应用包id
	PackageId *string `json:"package_id,omitempty"`
}
