/*
Oceanengine Open Api

巨量引擎开放平台 Open Api


*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package models

// ToolsAppManagementAppGetV2AccountAssetQueryScope
type ToolsAppManagementAppGetV2AccountAssetQueryScope string

// List of tools_app_management_app_get_v2_account_asset_query_scope
const (
	ACCOCUNT_ToolsAppManagementAppGetV2AccountAssetQueryScope ToolsAppManagementAppGetV2AccountAssetQueryScope = "ACCOCUNT"
	ALL_ToolsAppManagementAppGetV2AccountAssetQueryScope      ToolsAppManagementAppGetV2AccountAssetQueryScope = "ALL"
	GROUP_ToolsAppManagementAppGetV2AccountAssetQueryScope    ToolsAppManagementAppGetV2AccountAssetQueryScope = "GROUP"
)

// Ptr returns reference to tools_app_management_app_get_v2_account_asset_query_scope value
func (v ToolsAppManagementAppGetV2AccountAssetQueryScope) Ptr() *ToolsAppManagementAppGetV2AccountAssetQueryScope {
	return &v
}
