/*
Oceanengine Open Api

巨量引擎开放平台 Open Api


*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package models

// EventManagerOptimizedGoalGetV30MicroPromotionType
type EventManagerOptimizedGoalGetV30MicroPromotionType string

// List of event_manager_optimized_goal_get_v3.0_micro_promotion_type
const (
	AWEME_EventManagerOptimizedGoalGetV30MicroPromotionType       EventManagerOptimizedGoalGetV30MicroPromotionType = "AWEME"
	BYTE_APP_EventManagerOptimizedGoalGetV30MicroPromotionType    EventManagerOptimizedGoalGetV30MicroPromotionType = "BYTE_APP"
	BYTE_GAME_EventManagerOptimizedGoalGetV30MicroPromotionType   EventManagerOptimizedGoalGetV30MicroPromotionType = "BYTE_GAME"
	WECHAT_APP_EventManagerOptimizedGoalGetV30MicroPromotionType  EventManagerOptimizedGoalGetV30MicroPromotionType = "WECHAT_APP"
	WECHAT_GAME_EventManagerOptimizedGoalGetV30MicroPromotionType EventManagerOptimizedGoalGetV30MicroPromotionType = "WECHAT_GAME"
)

// Ptr returns reference to event_manager_optimized_goal_get_v3.0_micro_promotion_type value
func (v EventManagerOptimizedGoalGetV30MicroPromotionType) Ptr() *EventManagerOptimizedGoalGetV30MicroPromotionType {
	return &v
}
