/*
Oceanengine Open Api

巨量引擎开放平台 Open Api


*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package models

// StarMcnProviderGetRecruitInfoGetV2ResponseDataDemand
type StarMcnProviderGetRecruitInfoGetV2ResponseDataDemand struct {
	//
	AttachmentDescription *string `json:"attachment_description,omitempty"`
	//
	Brands []string `json:"brands,omitempty"`
	//
	FirstClassCategoryName *string `json:"first_class_category_name,omitempty"`
	//
	MissionNameForDemander *string `json:"mission_name_for_demander,omitempty"`
	//
	Name *string `json:"name,omitempty"`
	//
	Other          *string                                                             `json:"other,omitempty"`
	SrvProductInfo *StarMcnProviderGetRecruitInfoGetV2ResponseDataDemandSrvProductInfo `json:"srv_product_info,omitempty"`
}
