/*
Oceanengine Open Api

巨量引擎开放平台 Open Api


*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package models

// PromotionUpdateV30PromotionMaterialsProductInfoProductSellingPointType
type PromotionUpdateV30PromotionMaterialsProductInfoProductSellingPointType string

// List of promotion_update_v3.0_promotion_materials_product_info_product_selling_point_type
const (
	CUSTOM_PromotionUpdateV30PromotionMaterialsProductInfoProductSellingPointType PromotionUpdateV30PromotionMaterialsProductInfoProductSellingPointType = "CUSTOM"
	DPA_PromotionUpdateV30PromotionMaterialsProductInfoProductSellingPointType    PromotionUpdateV30PromotionMaterialsProductInfoProductSellingPointType = "DPA"
)

// Ptr returns reference to promotion_update_v3.0_promotion_materials_product_info_product_selling_point_type value
func (v PromotionUpdateV30PromotionMaterialsProductInfoProductSellingPointType) Ptr() *PromotionUpdateV30PromotionMaterialsProductInfoProductSellingPointType {
	return &v
}
