/*
Oceanengine Open Api

巨量引擎开放平台 Open Api


*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package models

// GoingGlobalUpdateV30RequestProjectListInner struct for GoingGlobalUpdateV30RequestProjectListInner
type GoingGlobalUpdateV30RequestProjectListInner struct {
	//
	GoingGlobalBudget *float64 `json:"going_global_budget,omitempty"`
	//
	GoingGlobalRoiGoal *float64                                          `json:"going_global_roi_goal,omitempty"`
	GoingGlobalSwitch  *GoingGlobalUpdateV30ProjectListGoingGlobalSwitch `json:"going_global_switch,omitempty"`
	//
	ProjectId int64 `json:"project_id"`
}
