/*
Oceanengine Open Api

巨量引擎开放平台 Open Api


*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package models

// QianchuanReportUniPromotionDimensionDataRoomGetV10Filtering
type QianchuanReportUniPromotionDimensionDataRoomGetV10Filtering struct {
	OrderPlatform *QianchuanReportUniPromotionDimensionDataRoomGetV10FilteringOrderPlatform `json:"order_platform,omitempty"`
	SmartBidType  *QianchuanReportUniPromotionDimensionDataRoomGetV10FilteringSmartBidType  `json:"smart_bid_type,omitempty"`
}
