/*
Oceanengine Open Api

巨量引擎开放平台 Open Api


*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package models

// StdProjectCreateV30ProjectMaterialsImageMaterialListImageMode
type StdProjectCreateV30ProjectMaterialsImageMaterialListImageMode string

// List of std_project_create_v3.0_project_materials_image_material_list_image_mode
const (
	CREATIVE_IMAGE_MODE_LARGE_StdProjectCreateV30ProjectMaterialsImageMaterialListImageMode          StdProjectCreateV30ProjectMaterialsImageMaterialListImageMode = "CREATIVE_IMAGE_MODE_LARGE"
	CREATIVE_IMAGE_MODE_LARGE_VERTICAL_StdProjectCreateV30ProjectMaterialsImageMaterialListImageMode StdProjectCreateV30ProjectMaterialsImageMaterialListImageMode = "CREATIVE_IMAGE_MODE_LARGE_VERTICAL"
	CREATIVE_IMAGE_MODE_SMALL_StdProjectCreateV30ProjectMaterialsImageMaterialListImageMode          StdProjectCreateV30ProjectMaterialsImageMaterialListImageMode = "CREATIVE_IMAGE_MODE_SMALL"
	SEARCH_AD_SMALL_IMAGE_StdProjectCreateV30ProjectMaterialsImageMaterialListImageMode              StdProjectCreateV30ProjectMaterialsImageMaterialListImageMode = "SEARCH_AD_SMALL_IMAGE"
	TOUTIAO_SEARCH_AD_IMAGE_StdProjectCreateV30ProjectMaterialsImageMaterialListImageMode            StdProjectCreateV30ProjectMaterialsImageMaterialListImageMode = "TOUTIAO_SEARCH_AD_IMAGE"
)

// Ptr returns reference to std_project_create_v3.0_project_materials_image_material_list_image_mode value
func (v StdProjectCreateV30ProjectMaterialsImageMaterialListImageMode) Ptr() *StdProjectCreateV30ProjectMaterialsImageMaterialListImageMode {
	return &v
}
