/*
Oceanengine Open Api

巨量引擎开放平台 Open Api


*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package models

// ReportLiveRoomFlowCategoryGetV2OrderType
type ReportLiveRoomFlowCategoryGetV2OrderType string

// List of report_live_room_flow_category_get_v2_order_type
const (
	ASC_ReportLiveRoomFlowCategoryGetV2OrderType  ReportLiveRoomFlowCategoryGetV2OrderType = "ASC"
	DESC_ReportLiveRoomFlowCategoryGetV2OrderType ReportLiveRoomFlowCategoryGetV2OrderType = "DESC"
)

// Ptr returns reference to report_live_room_flow_category_get_v2_order_type value
func (v ReportLiveRoomFlowCategoryGetV2OrderType) Ptr() *ReportLiveRoomFlowCategoryGetV2OrderType {
	return &v
}
