/*
Oceanengine Open Api

巨量引擎开放平台 Open Api


*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package models

// FileVideoAdV2ResponseData
type FileVideoAdV2ResponseData struct {
	// 视频时长
	Duration *float64 `json:"duration,omitempty"`
	// 视频高度
	Height *int64 `json:"height,omitempty"`
	// 素材id，即多合一报表中的素材id，一个素材唯一对应一个素材id
	MaterialId *int64 `json:"material_id,omitempty"`
	// 视频大小
	Size *int64 `json:"size,omitempty"`
	// 视频ID
	VideoId *string `json:"video_id,omitempty"`
	//
	VideoSignature *string `json:"video_signature,omitempty"`
	// 视频地址
	VideoUrl *string `json:"video_url,omitempty"`
	// 视频宽度
	Width *int64 `json:"width,omitempty"`
}
