/*
Oceanengine Open Api

巨量引擎开放平台 Open Api


*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package models

// StdProjectUpdateV30IsCommentDisable
type StdProjectUpdateV30IsCommentDisable string

// List of std_project_update_v3.0_is_comment_disable
const (
	OFF_StdProjectUpdateV30IsCommentDisable StdProjectUpdateV30IsCommentDisable = "OFF"
	ON_StdProjectUpdateV30IsCommentDisable  StdProjectUpdateV30IsCommentDisable = "ON"
)

// Ptr returns reference to std_project_update_v3.0_is_comment_disable value
func (v StdProjectUpdateV30IsCommentDisable) Ptr() *StdProjectUpdateV30IsCommentDisable {
	return &v
}
