/*
Oceanengine Open Api

巨量引擎开放平台 Open Api


*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package models

// DouplusRtaGetInfoV30ResponseData
type DouplusRtaGetInfoV30ResponseData struct {
	Interface *DouplusRtaGetInfoV30ResponseDataInterface `json:"interface,omitempty"`
	//
	RtaList []*DouplusRtaGetInfoV30ResponseDataRtaListInner `json:"rta_list,omitempty"`
	//
	Total *int64 `json:"total,omitempty"`
}
