/*
Oceanengine Open Api

巨量引擎开放平台 Open Api


*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package models

// QueryInvoiceElectronicUrlSelfV2ResponseData
type QueryInvoiceElectronicUrlSelfV2ResponseData struct {
	//
	UrlList []*QueryInvoiceElectronicUrlSelfV2ResponseDataUrlListInner `json:"url_list,omitempty"`
}
