/*
Oceanengine Open Api

巨量引擎开放平台 Open Api


*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package models

// ToolsEbpAppUpdateV30ScheduleCards
type ToolsEbpAppUpdateV30ScheduleCards string

// List of tools_ebp_app_update_v3.0_schedule_cards
const (
	ANNUAL_ToolsEbpAppUpdateV30ScheduleCards    ToolsEbpAppUpdateV30ScheduleCards = "Annual"
	LIFETIME_ToolsEbpAppUpdateV30ScheduleCards  ToolsEbpAppUpdateV30ScheduleCards = "Lifetime"
	MONTHLY_ToolsEbpAppUpdateV30ScheduleCards   ToolsEbpAppUpdateV30ScheduleCards = "Monthly"
	NONE_ToolsEbpAppUpdateV30ScheduleCards      ToolsEbpAppUpdateV30ScheduleCards = "None"
	QUARTERLY_ToolsEbpAppUpdateV30ScheduleCards ToolsEbpAppUpdateV30ScheduleCards = "Quarterly"
	WEEKLY_ToolsEbpAppUpdateV30ScheduleCards    ToolsEbpAppUpdateV30ScheduleCards = "Weekly"
)

// Ptr returns reference to tools_ebp_app_update_v3.0_schedule_cards value
func (v ToolsEbpAppUpdateV30ScheduleCards) Ptr() *ToolsEbpAppUpdateV30ScheduleCards {
	return &v
}
