/*
Oceanengine Open Api

巨量引擎开放平台 Open Api


*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package models

// SharedWalletWalletAdvOperationLogGetV30DataListWalletOperationType 操作类型
type SharedWalletWalletAdvOperationLogGetV30DataListWalletOperationType string

// List of shared_wallet_wallet_adv_operation_log_get_v3.0_data_list_wallet_operation_type
const (
	BIND_SharedWalletWalletAdvOperationLogGetV30DataListWalletOperationType   SharedWalletWalletAdvOperationLogGetV30DataListWalletOperationType = "bind"
	UNBIND_SharedWalletWalletAdvOperationLogGetV30DataListWalletOperationType SharedWalletWalletAdvOperationLogGetV30DataListWalletOperationType = "unbind"
)

// Ptr returns reference to shared_wallet_wallet_adv_operation_log_get_v3.0_data_list_wallet_operation_type value
func (v SharedWalletWalletAdvOperationLogGetV30DataListWalletOperationType) Ptr() *SharedWalletWalletAdvOperationLogGetV30DataListWalletOperationType {
	return &v
}
