/*
Oceanengine Open Api

巨量引擎开放平台 Open Api

API version: 1.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package models

// ToolsKeyActionGetV2ResponseData
type ToolsKeyActionGetV2ResponseData struct {
	//
	List []map[string]interface{} `json:"list,omitempty"`
	//
	PageInfo map[string]interface{} `json:"page_info,omitempty"`
}
