/*
Oceanengine Open Api

巨量引擎开放平台 Open Api


*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package models

// ToolsClueFormDetailV2DataElementsIsUnique
type ToolsClueFormDetailV2DataElementsIsUnique int64

// List of tools_clue_form_detail_v2_data_elements_is_unique
const (
	Enum_0_ToolsClueFormDetailV2DataElementsIsUnique ToolsClueFormDetailV2DataElementsIsUnique = 0
	Enum_1_ToolsClueFormDetailV2DataElementsIsUnique ToolsClueFormDetailV2DataElementsIsUnique = 1
)

// Ptr returns reference to tools_clue_form_detail_v2_data_elements_is_unique value
func (v ToolsClueFormDetailV2DataElementsIsUnique) Ptr() *ToolsClueFormDetailV2DataElementsIsUnique {
	return &v
}
