/*
Oceanengine Open Api

巨量引擎开放平台 Open Api


*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package models

// QianchuanReportUniPromotionDimensionDataAuthorGetV10Dimension
type QianchuanReportUniPromotionDimensionDataAuthorGetV10Dimension string

// List of qianchuan_report_uni_promotion_dimension_data_author_get_v1.0_dimension
const (
	TIME_GRANULARITY_DAILY_QianchuanReportUniPromotionDimensionDataAuthorGetV10Dimension  QianchuanReportUniPromotionDimensionDataAuthorGetV10Dimension = "TIME_GRANULARITY_DAILY"
	TIME_GRANULARITY_HOURLY_QianchuanReportUniPromotionDimensionDataAuthorGetV10Dimension QianchuanReportUniPromotionDimensionDataAuthorGetV10Dimension = "TIME_GRANULARITY_HOURLY"
)

// Ptr returns reference to qianchuan_report_uni_promotion_dimension_data_author_get_v1.0_dimension value
func (v QianchuanReportUniPromotionDimensionDataAuthorGetV10Dimension) Ptr() *QianchuanReportUniPromotionDimensionDataAuthorGetV10Dimension {
	return &v
}
