/*
Oceanengine Open Api

巨量引擎开放平台 Open Api


*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package models

// QianchuanAdDetailGetV10DataCreativeAutoGenerate
type QianchuanAdDetailGetV10DataCreativeAutoGenerate int64

// List of qianchuan_ad_detail_get_v1.0_data_creative_auto_generate
const (
	Enum_0_QianchuanAdDetailGetV10DataCreativeAutoGenerate QianchuanAdDetailGetV10DataCreativeAutoGenerate = 0
	Enum_1_QianchuanAdDetailGetV10DataCreativeAutoGenerate QianchuanAdDetailGetV10DataCreativeAutoGenerate = 1
)

// Ptr returns reference to qianchuan_ad_detail_get_v1.0_data_creative_auto_generate value
func (v QianchuanAdDetailGetV10DataCreativeAutoGenerate) Ptr() *QianchuanAdDetailGetV10DataCreativeAutoGenerate {
	return &v
}
