/*
Oceanengine Open Api

巨量引擎开放平台 Open Api


*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package models

// QianchuanUniPromotionAdMaterialGetV10ResponseDataAdMaterialInfosInnerMaterialInfoCarouselMaterial
type QianchuanUniPromotionAdMaterialGetV10ResponseDataAdMaterialInfosInnerMaterialInfoCarouselMaterial struct {
	// 图文描述
	Description *string `json:"description,omitempty"`
	//
	Image []*QianchuanUniPromotionAdMaterialGetV10ResponseDataAdMaterialInfosInnerMaterialInfoCarouselMaterialImageInner `json:"image,omitempty"`
	// 素材id
	MaterialId *int64 `json:"material_id,omitempty"`
	//
	MusicUrl *string `json:"music_url,omitempty"`
	// 图文标题
	Title *string `json:"title,omitempty"`
}
