/*
Oceanengine Open Api

巨量引擎开放平台 Open Api


*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package models

// ReportCreativeGetV2FilteringDeliveryMode
type ReportCreativeGetV2FilteringDeliveryMode string

// List of report_creative_get_v2_filtering_delivery_mode
const (
	ADLAB_FREE_ReportCreativeGetV2FilteringDeliveryMode ReportCreativeGetV2FilteringDeliveryMode = "ADLAB_FREE"
	STANDARD_ReportCreativeGetV2FilteringDeliveryMode   ReportCreativeGetV2FilteringDeliveryMode = "STANDARD"
)

// Ptr returns reference to report_creative_get_v2_filtering_delivery_mode value
func (v ReportCreativeGetV2FilteringDeliveryMode) Ptr() *ReportCreativeGetV2FilteringDeliveryMode {
	return &v
}
