/*
Oceanengine Open Api

巨量引擎开放平台 Open Api


*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package models

// BrandAdGetV30AdStatus
type BrandAdGetV30AdStatus int64

// List of brand_ad_get_v3.0_ad_status
const (
	Enum_1_BrandAdGetV30AdStatus  BrandAdGetV30AdStatus = 1
	Enum_10_BrandAdGetV30AdStatus BrandAdGetV30AdStatus = 10
	Enum_11_BrandAdGetV30AdStatus BrandAdGetV30AdStatus = 11
	Enum_12_BrandAdGetV30AdStatus BrandAdGetV30AdStatus = 12
	Enum_2_BrandAdGetV30AdStatus  BrandAdGetV30AdStatus = 2
	Enum_3_BrandAdGetV30AdStatus  BrandAdGetV30AdStatus = 3
	Enum_4_BrandAdGetV30AdStatus  BrandAdGetV30AdStatus = 4
	Enum_5_BrandAdGetV30AdStatus  BrandAdGetV30AdStatus = 5
	Enum_6_BrandAdGetV30AdStatus  BrandAdGetV30AdStatus = 6
	Enum_7_BrandAdGetV30AdStatus  BrandAdGetV30AdStatus = 7
	Enum_8_BrandAdGetV30AdStatus  BrandAdGetV30AdStatus = 8
	Enum_9_BrandAdGetV30AdStatus  BrandAdGetV30AdStatus = 9
)

// Ptr returns reference to brand_ad_get_v3.0_ad_status value
func (v BrandAdGetV30AdStatus) Ptr() *BrandAdGetV30AdStatus {
	return &v
}
