/*
Oceanengine Open Api

巨量引擎开放平台 Open Api


*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package models

// PrepayChargeGenerateFixRemiattanceCodeCreateV30Caller 请求方
type PrepayChargeGenerateFixRemiattanceCodeCreateV30Caller string

// List of prepay_charge_generate_fix_remiattance_code_create_v3.0_caller
const (
	MAPI_PrepayChargeGenerateFixRemiattanceCodeCreateV30Caller PrepayChargeGenerateFixRemiattanceCodeCreateV30Caller = "MAPI"
)

// Ptr returns reference to prepay_charge_generate_fix_remiattance_code_create_v3.0_caller value
func (v PrepayChargeGenerateFixRemiattanceCodeCreateV30Caller) Ptr() *PrepayChargeGenerateFixRemiattanceCodeCreateV30Caller {
	return &v
}
