/*
Oceanengine Open Api

巨量引擎开放平台 Open Api


*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package models

// PromotionListV30FilteringBlueFlowPackageSetting
type PromotionListV30FilteringBlueFlowPackageSetting string

// List of promotion_list_v3.0_filtering_blue_flow_package_setting
const (
	OFF_PromotionListV30FilteringBlueFlowPackageSetting PromotionListV30FilteringBlueFlowPackageSetting = "OFF"
	ON_PromotionListV30FilteringBlueFlowPackageSetting  PromotionListV30FilteringBlueFlowPackageSetting = "ON"
)

// Ptr returns reference to promotion_list_v3.0_filtering_blue_flow_package_setting value
func (v PromotionListV30FilteringBlueFlowPackageSetting) Ptr() *PromotionListV30FilteringBlueFlowPackageSetting {
	return &v
}
