/*
Oceanengine Open Api

巨量引擎开放平台 Open Api


*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package models

// AicMixcutTaskSaveV30Request struct for AicMixcutTaskSaveV30Request
type AicMixcutTaskSaveV30Request struct {
	// BP账户体系:组织id，Agent账户体系:代理商id
	AccountId   int64                           `json:"account_id"`
	AccountType AicMixcutTaskSaveV30AccountType `json:"account_type"`
	// 需要保存的视频数组，数量限制:50
	Videos []*AicMixcutTaskSaveV30RequestVideosInner `json:"videos"`
}
