/*
Oceanengine Open Api

巨量引擎开放平台 Open Api


*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package models

// ToolsPromotionRaiseStatusGetV30ResponseDataListInner struct for ToolsPromotionRaiseStatusGetV30ResponseDataListInner
type ToolsPromotionRaiseStatusGetV30ResponseDataListInner struct {
	// 起量信息
	RaiseInfo []*ToolsPromotionRaiseStatusGetV30ResponseDataListInnerRaiseInfoInner `json:"raise_info,omitempty"`
}
