/*
Oceanengine Open Api

巨量引擎开放平台 Open Api


*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package models

// AdUpdateBudgetV2ResponseDataErrorsInner struct for AdUpdateBudgetV2ResponseDataErrorsInner
type AdUpdateBudgetV2ResponseDataErrorsInner struct {
	//
	AdId *int64 `json:"ad_id,omitempty"`
	//
	ErrorMessage *string `json:"error_message,omitempty"`
}
