/*
Oceanengine Open Api

巨量引擎开放平台 Open Api

API version: 1.1.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package models

// ToolsEstimateAudienceV2ResponseDataVideoApp
type ToolsEstimateAudienceV2ResponseDataVideoApp struct {
	//
	Num *int64 `json:"num,omitempty"`
}
