/*
Oceanengine Open Api

巨量引擎开放平台 Open Api


*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package models

// QianchuanUniPromotionAdSuggestionV10ResponseDataListInnerImageMaterial 图片素材
type QianchuanUniPromotionAdSuggestionV10ResponseDataListInnerImageMaterial struct {
	//
	Height *int64 `json:"height,omitempty"`
	// 图片ID
	ImageId   *string                                                             `json:"image_id,omitempty"`
	ImageMode *QianchuanUniPromotionAdSuggestionV10DataListImageMaterialImageMode `json:"image_mode,omitempty"`
	// 图片链接
	ImageUrl *string `json:"image_url,omitempty"`
	//
	Width *int64 `json:"width,omitempty"`
}
