/*
Oceanengine Open Api

巨量引擎开放平台 Open Api


*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package models

// ProjectCreateV30DeliveryMode
type ProjectCreateV30DeliveryMode string

// List of project_create_v3.0_delivery_mode
const (
	MANUAL_ProjectCreateV30DeliveryMode     ProjectCreateV30DeliveryMode = "MANUAL"
	PROCEDURAL_ProjectCreateV30DeliveryMode ProjectCreateV30DeliveryMode = "PROCEDURAL"
)

// Ptr returns reference to project_create_v3.0_delivery_mode value
func (v ProjectCreateV30DeliveryMode) Ptr() *ProjectCreateV30DeliveryMode {
	return &v
}
