/*
Oceanengine Open Api

巨量引擎开放平台 Open Api


*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package models

// ToolsAppManagementAndroidBasicPackageUpdateV2Request struct for ToolsAppManagementAndroidBasicPackageUpdateV2Request
type ToolsAppManagementAndroidBasicPackageUpdateV2Request struct {
	// 账户id指可以接的账号体系如广告主id、巨量纵横组织id等
	AccountId   int64                                                    `json:"account_id"`
	AccountType ToolsAppManagementAndroidBasicPackageUpdateV2AccountType `json:"account_type"`
	// 应用介绍
	AppDescription string `json:"app_description"`
	// 应用开发者名称
	AppDeveloperName string `json:"app_developer_name"`
	// 应用名称
	AppName string `json:"app_name"`
	//
	ArtStyle *string `json:"art_style,omitempty"`
	// 是否自动发布
	AutoPublish bool `json:"auto_publish"`
	//
	CategoryId *int64 `json:"category_id,omitempty"`
	//
	DiscountRate *int64 `json:"discount_rate,omitempty"`
	//
	FeatureTags []string                                                `json:"feature_tags,omitempty"`
	FileOption  ToolsAppManagementAndroidBasicPackageUpdateV2FileOption `json:"file_option"`
	// 文件内容<br>必须包含一个apk；可选：五个图片、一个视频
	Files []*ToolsAppManagementAndroidBasicPackageUpdateV2RequestFilesInner `json:"files"`
	//
	GameBoxName *string `json:"game_box_name,omitempty"`
	//
	GameIpTag *string `json:"game_ip_tag,omitempty"`
	//
	GameIpType []*ToolsAppManagementAndroidBasicPackageUpdateV2GameIpType `json:"game_ip_type,omitempty"`
	//
	HasDiscount *bool `json:"has_discount,omitempty"`
	//
	HasOnlineEarning    *bool                                                             `json:"has_online_earning,omitempty"`
	MaxPaymentTierRange *ToolsAppManagementAndroidBasicPackageUpdateV2MaxPaymentTierRange `json:"max_payment_tier_range,omitempty"`
	MaxRechargeTier     *ToolsAppManagementAndroidBasicPackageUpdateV2MaxRechargeTier     `json:"max_recharge_tier,omitempty"`
	MembershipType      *ToolsAppManagementAndroidBasicPackageUpdateV2MembershipType      `json:"membership_type,omitempty"`
	MidPaymentTierRange *ToolsAppManagementAndroidBasicPackageUpdateV2MidPaymentTierRange `json:"mid_payment_tier_range,omitempty"`
	MinPaymentTierRange *ToolsAppManagementAndroidBasicPackageUpdateV2MinPaymentTierRange `json:"min_payment_tier_range,omitempty"`
	MinRechargeTier     *ToolsAppManagementAndroidBasicPackageUpdateV2MinRechargeTier     `json:"min_recharge_tier,omitempty"`
	//
	NetworkEnvironment []string `json:"network_environment,omitempty"`
	// 应用包id
	PackageId   string                                                   `json:"package_id"`
	PaymentType ToolsAppManagementAndroidBasicPackageUpdateV2PaymentType `json:"payment_type"`
	// 隐私权限说明
	PermissionsDescription string `json:"permissions_description"`
	// 推荐语
	Recommend               string                                                                `json:"recommend"`
	RecommendedRechargeTier *ToolsAppManagementAndroidBasicPackageUpdateV2RecommendedRechargeTier `json:"recommended_recharge_tier,omitempty"`
	RevenueModel            *ToolsAppManagementAndroidBasicPackageUpdateV2RevenueModel            `json:"revenue_model,omitempty"`
	//
	ScheduleCards []*ToolsAppManagementAndroidBasicPackageUpdateV2ScheduleCards `json:"schedule_cards,omitempty"`
	//
	Spokesperson *string `json:"spokesperson,omitempty"`
	// 应用题材标签id
	ThemeTagId *string `json:"theme_tag_id,omitempty"`
	// 版本更新说明
	UpdateDescription string `json:"update_description"`
}
