/*
Oceanengine Open Api

巨量引擎开放平台 Open Api


*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package models

// BrandMaterialListV30ResponseDataMaterialsInnerMaterialComponentAppDownloadAvatar 应用头像
type BrandMaterialListV30ResponseDataMaterialsInnerMaterialComponentAppDownloadAvatar struct {
	// 图片格式:jpg/jpeg/png/gif
	Format *string `json:"format,omitempty"`
	// hash
	Hash *string `json:"hash,omitempty"`
	// 图片高度
	Height *int64 `json:"height,omitempty"`
	// 图片地址
	WebUri *string `json:"web_uri,omitempty"`
	// 图片前端展示地址
	WebUriShowUrl *string `json:"web_uri_show_url,omitempty"`
	// 图片宽度
	Width *int64 `json:"width,omitempty"`
}
