/*
Oceanengine Open Api

巨量引擎开放平台 Open Api


*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package models

// ReportCreativeGetV2DataListRealRecallMatchType
type ReportCreativeGetV2DataListRealRecallMatchType string

// List of report_creative_get_v2_data_list_real_recall_match_type
const (
	EXTENSIVE_ReportCreativeGetV2DataListRealRecallMatchType ReportCreativeGetV2DataListRealRecallMatchType = "EXTENSIVE"
	PRECISION_ReportCreativeGetV2DataListRealRecallMatchType ReportCreativeGetV2DataListRealRecallMatchType = "PRECISION"
	PHRASE_ReportCreativeGetV2DataListRealRecallMatchType    ReportCreativeGetV2DataListRealRecallMatchType = "PHRASE"
)

// Ptr returns reference to report_creative_get_v2_data_list_real_recall_match_type value
func (v ReportCreativeGetV2DataListRealRecallMatchType) Ptr() *ReportCreativeGetV2DataListRealRecallMatchType {
	return &v
}
