/*
Oceanengine Open Api

巨量引擎开放平台 Open Api


*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package models

// ToolsBidSuggestV2Platform
type ToolsBidSuggestV2Platform string

// List of tools_bid_suggest_v2_platform
const (
	WAP_ToolsBidSuggestV2Platform     ToolsBidSuggestV2Platform = "WAP"
	NONE_ToolsBidSuggestV2Platform    ToolsBidSuggestV2Platform = "NONE"
	IPAD_ToolsBidSuggestV2Platform    ToolsBidSuggestV2Platform = "IPAD"
	PC_ToolsBidSuggestV2Platform      ToolsBidSuggestV2Platform = "PC"
	ANDROID_ToolsBidSuggestV2Platform ToolsBidSuggestV2Platform = "ANDROID"
	IOS_ToolsBidSuggestV2Platform     ToolsBidSuggestV2Platform = "IOS"
)

// Ptr returns reference to tools_bid_suggest_v2_platform value
func (v ToolsBidSuggestV2Platform) Ptr() *ToolsBidSuggestV2Platform {
	return &v
}
