/*
Oceanengine Open Api

巨量引擎开放平台 Open Api


*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package models

// QianchuanAdKeywordsGetV10Filtering
type QianchuanAdKeywordsGetV10Filtering struct {
	// 需要获取关键词的计划ID
	AdId int64 `json:"ad_id"`
}
