/*
Oceanengine Open Api

巨量引擎开放平台 Open Api


*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package models

// LocalProjectDetailV30DataPeakHolidays
type LocalProjectDetailV30DataPeakHolidays string

// List of local_project_detail_v3.0_data_peak_holidays
const (
	CHINESE_VALENTINES_DAY_LocalProjectDetailV30DataPeakHolidays LocalProjectDetailV30DataPeakHolidays = "CHINESE_VALENTINES_DAY"
	CHRISTMAS_LocalProjectDetailV30DataPeakHolidays              LocalProjectDetailV30DataPeakHolidays = "CHRISTMAS"
	DRAGON_BOAT_FESTIVAL_LocalProjectDetailV30DataPeakHolidays   LocalProjectDetailV30DataPeakHolidays = "DRAGON_BOAT_FESTIVAL"
	LABOUR_DAY_LocalProjectDetailV30DataPeakHolidays             LocalProjectDetailV30DataPeakHolidays = "LABOUR_DAY"
	MOON_FESTIVAL_LocalProjectDetailV30DataPeakHolidays          LocalProjectDetailV30DataPeakHolidays = "MOON_FESTIVAL"
	NATIONAL_DAY_LocalProjectDetailV30DataPeakHolidays           LocalProjectDetailV30DataPeakHolidays = "NATIONAL_DAY"
	NEW_YEAR_LocalProjectDetailV30DataPeakHolidays               LocalProjectDetailV30DataPeakHolidays = "NEW_YEAR"
	SHOPPING_DAY_1111_LocalProjectDetailV30DataPeakHolidays      LocalProjectDetailV30DataPeakHolidays = "SHOPPING_DAY_1111"
	SHOPPING_DAY_618_LocalProjectDetailV30DataPeakHolidays       LocalProjectDetailV30DataPeakHolidays = "SHOPPING_DAY_618"
	SPRING_FESTIVAL_LocalProjectDetailV30DataPeakHolidays        LocalProjectDetailV30DataPeakHolidays = "SPRING_FESTIVAL"
	VALENTINES_DAY_LocalProjectDetailV30DataPeakHolidays         LocalProjectDetailV30DataPeakHolidays = "VALENTINES_DAY"
)

// Ptr returns reference to local_project_detail_v3.0_data_peak_holidays value
func (v LocalProjectDetailV30DataPeakHolidays) Ptr() *LocalProjectDetailV30DataPeakHolidays {
	return &v
}
