/*
Oceanengine Open Api

巨量引擎开放平台 Open Api


*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package models

// ToolsCreativeWordSelectV2ResponseData
type ToolsCreativeWordSelectV2ResponseData struct {
	//
	CreativeWord []*ToolsCreativeWordSelectV2ResponseDataCreativeWordInner `json:"creative_word,omitempty"`
}
