/*
Oceanengine Open Api

巨量引擎开放平台 Open Api


*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package models

// BrandMaterialListV30ResponseDataMaterialsInnerMaterialComponentStaticTwistEgg 静态扭转
type BrandMaterialListV30ResponseDataMaterialsInnerMaterialComponentStaticTwistEgg struct {
	// 是否开启
	Enable      *bool                                                                                     `json:"enable,omitempty"`
	FarImage    *BrandMaterialListV30ResponseDataMaterialsInnerMaterialComponentStaticTwistEggFarImage    `json:"far_image,omitempty"`
	MediumImage *BrandMaterialListV30ResponseDataMaterialsInnerMaterialComponentStaticTwistEggMediumImage `json:"medium_image,omitempty"`
	NearImage   *BrandMaterialListV30ResponseDataMaterialsInnerMaterialComponentStaticTwistEggNearImage   `json:"near_image,omitempty"`
}
