/*
Oceanengine Open Api

巨量引擎开放平台 Open Api


*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package models

// BrandPolicyListV30AudienceInfoDistrictInfoCitySelectType 城市选择
type BrandPolicyListV30AudienceInfoDistrictInfoCitySelectType string

// List of brand_policy_list_v3.0_audience_info_district_info_city_select_type
const (
	EXCLUDE_BrandPolicyListV30AudienceInfoDistrictInfoCitySelectType BrandPolicyListV30AudienceInfoDistrictInfoCitySelectType = "EXCLUDE"
	SELECT_BrandPolicyListV30AudienceInfoDistrictInfoCitySelectType  BrandPolicyListV30AudienceInfoDistrictInfoCitySelectType = "SELECT"
)

// Ptr returns reference to brand_policy_list_v3.0_audience_info_district_info_city_select_type value
func (v BrandPolicyListV30AudienceInfoDistrictInfoCitySelectType) Ptr() *BrandPolicyListV30AudienceInfoDistrictInfoCitySelectType {
	return &v
}
