/*
Oceanengine Open Api

巨量引擎开放平台 Open Api


*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package models

// GameAddictionIdGetV30DataGameAddictionListSuggestion
type GameAddictionIdGetV30DataGameAddictionListSuggestion string

// List of game_addiction_id_get_v3.0_data_game_addiction_list_suggestion
const (
	ACTIVATION_LOW_BEHAVIOR_HIGH_GameAddictionIdGetV30DataGameAddictionListSuggestion GameAddictionIdGetV30DataGameAddictionListSuggestion = "ACTIVATION_LOW_BEHAVIOR_HIGH"
	ACTIVATION_LOW_BEHAVIOR_LOW_GameAddictionIdGetV30DataGameAddictionListSuggestion  GameAddictionIdGetV30DataGameAddictionListSuggestion = "ACTIVATION_LOW_BEHAVIOR_LOW"
	BEHAVIOR_ACTIVATION_LOW_GameAddictionIdGetV30DataGameAddictionListSuggestion      GameAddictionIdGetV30DataGameAddictionListSuggestion = "BEHAVIOR_ACTIVATION_LOW"
	NORMAL_GameAddictionIdGetV30DataGameAddictionListSuggestion                       GameAddictionIdGetV30DataGameAddictionListSuggestion = "NORMAL"
	NOT_PRE_STANDARD_GameAddictionIdGetV30DataGameAddictionListSuggestion             GameAddictionIdGetV30DataGameAddictionListSuggestion = "NOT_PRE_STANDARD"
	PAYMENT_ACTION_HIGH_GameAddictionIdGetV30DataGameAddictionListSuggestion          GameAddictionIdGetV30DataGameAddictionListSuggestion = "PAYMENT_ACTION_HIGH"
	PAYMENT_ACTION_LOW_GameAddictionIdGetV30DataGameAddictionListSuggestion           GameAddictionIdGetV30DataGameAddictionListSuggestion = "PAYMENT_ACTION_LOW"
)

// Ptr returns reference to game_addiction_id_get_v3.0_data_game_addiction_list_suggestion value
func (v GameAddictionIdGetV30DataGameAddictionListSuggestion) Ptr() *GameAddictionIdGetV30DataGameAddictionListSuggestion {
	return &v
}
