/*
Oceanengine Open Api

巨量引擎开放平台 Open Api


*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package models

// BrandAdCreateV30RequestAudienceInfo 定向
type BrandAdCreateV30RequestAudienceInfo struct {
	Ac *BrandAdCreateV30AudienceInfoAc `json:"ac,omitempty"`
	// 兴趣定向
	ActionCategory []int64 `json:"action_category,omitempty"`
	// 年龄定向，支持的枚举值：<br> BETWEEN18_23：18～23岁<br> BETWEEN24_30：24～30岁<br> BETWEEN31_40：31～40岁<br> BETWEEN41_49：41～49岁<br> ABOVE50：50岁及以上<br> UNLIMITED：不限
	Ages            []*BrandAdCreateV30AudienceInfoAges                 `json:"ages,omitempty"`
	DistrictInfo    *BrandAdCreateV30RequestAudienceInfoDistrictInfo    `json:"district_info,omitempty"`
	Gender          *BrandAdCreateV30AudienceInfoGender                 `json:"gender,omitempty"`
	Platform        *BrandAdCreateV30AudienceInfoPlatform               `json:"platform,omitempty"`
	RetargetingInfo *BrandAdCreateV30RequestAudienceInfoRetargetingInfo `json:"retargeting_info,omitempty"`
}
