/*
Oceanengine Open Api

巨量引擎开放平台 Open Api


*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package models

// BrandMaterialListV30ResponseDataMaterialsInnerMaterialComponentDynamicNoneFullScreen 动态-非全屏-图片
type BrandMaterialListV30ResponseDataMaterialsInnerMaterialComponentDynamicNoneFullScreen struct {
	// 静态底图
	ImageInfoBkList []*BrandMaterialListV30ResponseDataMaterialsInnerMaterialComponentDynamicNoneFullScreenImageInfoBkListInner `json:"image_info_bk_list,omitempty"`
	// 图片
	ImageInfoList []*BrandMaterialListV30ResponseDataMaterialsInnerMaterialComponentDynamicNoneFullScreenImageInfoListInner `json:"image_info_list,omitempty"`
}
