/*
Oceanengine Open Api

巨量引擎开放平台 Open Api


*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package models

// QianchuanAdMaterialSuggestionV10DataListAuditRecordsAuditPlatform
type QianchuanAdMaterialSuggestionV10DataListAuditRecordsAuditPlatform string

// List of qianchuan_ad_material_suggestion_v1.0_data_list_audit_records_audit_platform
const (
	UNKNOWN_QianchuanAdMaterialSuggestionV10DataListAuditRecordsAuditPlatform QianchuanAdMaterialSuggestionV10DataListAuditRecordsAuditPlatform = "UNKNOWN"
	AD_QianchuanAdMaterialSuggestionV10DataListAuditRecordsAuditPlatform      QianchuanAdMaterialSuggestionV10DataListAuditRecordsAuditPlatform = "AD"
	CONTENT_QianchuanAdMaterialSuggestionV10DataListAuditRecordsAuditPlatform QianchuanAdMaterialSuggestionV10DataListAuditRecordsAuditPlatform = "CONTENT"
)

// Ptr returns reference to qianchuan_ad_material_suggestion_v1.0_data_list_audit_records_audit_platform value
func (v QianchuanAdMaterialSuggestionV10DataListAuditRecordsAuditPlatform) Ptr() *QianchuanAdMaterialSuggestionV10DataListAuditRecordsAuditPlatform {
	return &v
}
