/*
Oceanengine Open Api

巨量引擎开放平台 Open Api


*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package models

// LocalPromotionDetailV30DataVideoHpVisibility 抖音主页可见性
type LocalPromotionDetailV30DataVideoHpVisibility string

// List of local_promotion_detail_v3.0_data_video_hp_visibility
const (
	ALWAYS_VISIBLE_LocalPromotionDetailV30DataVideoHpVisibility   LocalPromotionDetailV30DataVideoHpVisibility = "ALWAYS_VISIBLE"
	HIDE_VIDEO_ON_HP_LocalPromotionDetailV30DataVideoHpVisibility LocalPromotionDetailV30DataVideoHpVisibility = "HIDE_VIDEO_ON_HP"
)

// Ptr returns reference to local_promotion_detail_v3.0_data_video_hp_visibility value
func (v LocalPromotionDetailV30DataVideoHpVisibility) Ptr() *LocalPromotionDetailV30DataVideoHpVisibility {
	return &v
}
