/*
Oceanengine Open Api

巨量引擎开放平台 Open Api


*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package models

// DpaEbpProductDetailGetV30ResponseDataListInnerVideosInner struct for DpaEbpProductDetailGetV30ResponseDataListInnerVideosInner
type DpaEbpProductDetailGetV30ResponseDataListInnerVideosInner struct {
	//
	TemplateId *string `json:"template_id,omitempty"`
	//
	Url *string `json:"url,omitempty"`
}
