/*
Oceanengine Open Api

巨量引擎开放平台 Open Api


*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package models

// ToolsEbpAppDetailV30DataNextVersionGameIpType
type ToolsEbpAppDetailV30DataNextVersionGameIpType string

// List of tools_ebp_app_detail_v3.0_data_next_version_game_ip_type
const (
	ANIMATION_ToolsEbpAppDetailV30DataNextVersionGameIpType ToolsEbpAppDetailV30DataNextVersionGameIpType = "Animation"
	ARTISTIC_ToolsEbpAppDetailV30DataNextVersionGameIpType  ToolsEbpAppDetailV30DataNextVersionGameIpType = "Artistic"
	FILM_ToolsEbpAppDetailV30DataNextVersionGameIpType      ToolsEbpAppDetailV30DataNextVersionGameIpType = "Film"
	LITERARY_ToolsEbpAppDetailV30DataNextVersionGameIpType  ToolsEbpAppDetailV30DataNextVersionGameIpType = "Literary"
	NONE_ToolsEbpAppDetailV30DataNextVersionGameIpType      ToolsEbpAppDetailV30DataNextVersionGameIpType = "None"
	OTHERS_ToolsEbpAppDetailV30DataNextVersionGameIpType    ToolsEbpAppDetailV30DataNextVersionGameIpType = "Others"
)

// Ptr returns reference to tools_ebp_app_detail_v3.0_data_next_version_game_ip_type value
func (v ToolsEbpAppDetailV30DataNextVersionGameIpType) Ptr() *ToolsEbpAppDetailV30DataNextVersionGameIpType {
	return &v
}
