/*
Oceanengine Open Api

巨量引擎开放平台 Open Api


*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package models

// StdProjectListV30DataListStatusSecond
type StdProjectListV30DataListStatusSecond string

// List of std_project_list_v3.0_data_list_status_second
const (
	ADVERTISER_AVATAR_OFFLINE_StdProjectListV30DataListStatusSecond             StdProjectListV30DataListStatusSecond = "ADVERTISER_AVATAR_OFFLINE"
	APP_NOT_AVAILABLE_FOR_DELIVERY_StdProjectListV30DataListStatusSecond        StdProjectListV30DataListStatusSecond = "APP_NOT_AVAILABLE_FOR_DELIVERY"
	LACK_BASIC_MATERIAL_STATUS_StdProjectListV30DataListStatusSecond            StdProjectListV30DataListStatusSecond = "LACK_BASIC_MATERIAL_STATUS"
	LIVE_ROOM_NOT_AVAILABLE_FOR_DELIVERY_StdProjectListV30DataListStatusSecond  StdProjectListV30DataListStatusSecond = "LIVE_ROOM_NOT_AVAILABLE_FOR_DELIVERY"
	PROJECT_STATUS_ADV_OFFLINE_BUDGET_StdProjectListV30DataListStatusSecond     StdProjectListV30DataListStatusSecond = "PROJECT_STATUS_ADV_OFFLINE_BUDGET"
	PROJECT_STATUS_AUDIT_StdProjectListV30DataListStatusSecond                  StdProjectListV30DataListStatusSecond = "PROJECT_STATUS_AUDIT"
	PROJECT_STATUS_AWEME_ACCOUNT_DISABLED_StdProjectListV30DataListStatusSecond StdProjectListV30DataListStatusSecond = "PROJECT_STATUS_AWEME_ACCOUNT_DISABLED"
	PROJECT_STATUS_BUDGET_EXCEED_StdProjectListV30DataListStatusSecond          StdProjectListV30DataListStatusSecond = "PROJECT_STATUS_BUDGET_EXCEED"
	PROJECT_STATUS_NOT_START_StdProjectListV30DataListStatusSecond              StdProjectListV30DataListStatusSecond = "PROJECT_STATUS_NOT_START"
	PROJECT_STATUS_NO_SCHEDULE_StdProjectListV30DataListStatusSecond            StdProjectListV30DataListStatusSecond = "PROJECT_STATUS_NO_SCHEDULE"
	PROJECT_STATUS_OFFLINE_AUDIT_StdProjectListV30DataListStatusSecond          StdProjectListV30DataListStatusSecond = "PROJECT_STATUS_OFFLINE_AUDIT"
	PROJECT_STATUS_OFFLINE_BUDGET_StdProjectListV30DataListStatusSecond         StdProjectListV30DataListStatusSecond = "PROJECT_STATUS_OFFLINE_BUDGET"
	PROJECT_STATUS_PROCEDURAL_DISABLE_StdProjectListV30DataListStatusSecond     StdProjectListV30DataListStatusSecond = "PROJECT_STATUS_PROCEDURAL_DISABLE"
	PROJECT_STATUS_PRODUCT_OFFLINE_StdProjectListV30DataListStatusSecond        StdProjectListV30DataListStatusSecond = "PROJECT_STATUS_PRODUCT_OFFLINE"
	PROJECT_STATUS_REACH_DAILY_DELIVERY_StdProjectListV30DataListStatusSecond   StdProjectListV30DataListStatusSecond = "PROJECT_STATUS_REACH_DAILY_DELIVERY"
	PROJECT_STATUS_REAUDIT_StdProjectListV30DataListStatusSecond                StdProjectListV30DataListStatusSecond = "PROJECT_STATUS_REAUDIT"
	PROJECT_STATUS_STOP_StdProjectListV30DataListStatusSecond                   StdProjectListV30DataListStatusSecond = "PROJECT_STATUS_STOP"
	SHARED_WALLET_EXCEEDS_BUDGET_StdProjectListV30DataListStatusSecond          StdProjectListV30DataListStatusSecond = "SHARED_WALLET_EXCEEDS_BUDGET"
)

// Ptr returns reference to std_project_list_v3.0_data_list_status_second value
func (v StdProjectListV30DataListStatusSecond) Ptr() *StdProjectListV30DataListStatusSecond {
	return &v
}
