/*
Oceanengine Open Api

巨量引擎开放平台 Open Api


*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package models

// ProjectListV30FilteringAppPromotionType
type ProjectListV30FilteringAppPromotionType string

// List of project_list_v3.0_filtering_app_promotion_type
const (
	DOWNLOAD_ProjectListV30FilteringAppPromotionType ProjectListV30FilteringAppPromotionType = "DOWNLOAD"
	LAUNCH_ProjectListV30FilteringAppPromotionType   ProjectListV30FilteringAppPromotionType = "LAUNCH"
	RESERVE_ProjectListV30FilteringAppPromotionType  ProjectListV30FilteringAppPromotionType = "RESERVE"
)

// Ptr returns reference to project_list_v3.0_filtering_app_promotion_type value
func (v ProjectListV30FilteringAppPromotionType) Ptr() *ProjectListV30FilteringAppPromotionType {
	return &v
}
