/*
Oceanengine Open Api

巨量引擎开放平台 Open Api


*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package models

// OcProjectToolsAudienceListV30DataListGenderAudience 具体性别定向设置
type OcProjectToolsAudienceListV30DataListGenderAudience string

// List of oc_project_tools_audience_list_v3.0_data_list_gender_audience
const (
	GENDER_FEMALE_OcProjectToolsAudienceListV30DataListGenderAudience    OcProjectToolsAudienceListV30DataListGenderAudience = "GENDER_FEMALE"
	GENDER_MALE_OcProjectToolsAudienceListV30DataListGenderAudience      OcProjectToolsAudienceListV30DataListGenderAudience = "GENDER_MALE"
	GENDER_UNLIMITED_OcProjectToolsAudienceListV30DataListGenderAudience OcProjectToolsAudienceListV30DataListGenderAudience = "GENDER_UNLIMITED"
)

// Ptr returns reference to oc_project_tools_audience_list_v3.0_data_list_gender_audience value
func (v OcProjectToolsAudienceListV30DataListGenderAudience) Ptr() *OcProjectToolsAudienceListV30DataListGenderAudience {
	return &v
}
