/*
Oceanengine Open Api

巨量引擎开放平台 Open Api


*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package models

// ToolsEbpWechatGameListV30AssetManagementScope
type ToolsEbpWechatGameListV30AssetManagementScope string

// List of tools_ebp_wechat_game_list_v3.0_asset_management_scope
const (
	DIRECT_ToolsEbpWechatGameListV30AssetManagementScope   ToolsEbpWechatGameListV30AssetManagementScope = "DIRECT"
	TRAVERSE_ToolsEbpWechatGameListV30AssetManagementScope ToolsEbpWechatGameListV30AssetManagementScope = "TRAVERSE"
)

// Ptr returns reference to tools_ebp_wechat_game_list_v3.0_asset_management_scope value
func (v ToolsEbpWechatGameListV30AssetManagementScope) Ptr() *ToolsEbpWechatGameListV30AssetManagementScope {
	return &v
}
