/*
Oceanengine Open Api

巨量引擎开放平台 Open Api


*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package models

// EventManagerDbtGetV30DataDeepBidTypeDetailDeepBidType
type EventManagerDbtGetV30DataDeepBidTypeDetailDeepBidType string

// List of event_manager_dbt_get_v3.0_data_deep_bid_type_detail_deep_bid_type
const (
	ALI_FL_EventManagerDbtGetV30DataDeepBidTypeDetailDeepBidType                       EventManagerDbtGetV30DataDeepBidTypeDetailDeepBidType = "ALI_FL"
	AUTO_MIN_SECOND_STAGE_EventManagerDbtGetV30DataDeepBidTypeDetailDeepBidType        EventManagerDbtGetV30DataDeepBidTypeDetailDeepBidType = "AUTO_MIN_SECOND_STAGE"
	BID_PER_ACTION_EventManagerDbtGetV30DataDeepBidTypeDetailDeepBidType               EventManagerDbtGetV30DataDeepBidTypeDetailDeepBidType = "BID_PER_ACTION"
	DEEP_BID_DEFAULT_EventManagerDbtGetV30DataDeepBidTypeDetailDeepBidType             EventManagerDbtGetV30DataDeepBidTypeDetailDeepBidType = "DEEP_BID_DEFAULT"
	DEEP_BID_MIN_EventManagerDbtGetV30DataDeepBidTypeDetailDeepBidType                 EventManagerDbtGetV30DataDeepBidTypeDetailDeepBidType = "DEEP_BID_MIN"
	DEEP_BID_PACING_EventManagerDbtGetV30DataDeepBidTypeDetailDeepBidType              EventManagerDbtGetV30DataDeepBidTypeDetailDeepBidType = "DEEP_BID_PACING"
	DEEP_BID_TYPE_RETENTION_DAYS_EventManagerDbtGetV30DataDeepBidTypeDetailDeepBidType EventManagerDbtGetV30DataDeepBidTypeDetailDeepBidType = "DEEP_BID_TYPE_RETENTION_DAYS"
	FIRST_AND_SEVEN_PAY_ROI_EventManagerDbtGetV30DataDeepBidTypeDetailDeepBidType      EventManagerDbtGetV30DataDeepBidTypeDetailDeepBidType = "FIRST_AND_SEVEN_PAY_ROI"
	FORM_BID_EventManagerDbtGetV30DataDeepBidTypeDetailDeepBidType                     EventManagerDbtGetV30DataDeepBidTypeDetailDeepBidType = "FORM_BID"
	IAAP_ROI_24_H_AND_7_D_EventManagerDbtGetV30DataDeepBidTypeDetailDeepBidType        EventManagerDbtGetV30DataDeepBidTypeDetailDeepBidType = "IAAP_ROI_24H_AND_7D"
	IAAP_SEVEN_ROI_COEFFICIENT_EventManagerDbtGetV30DataDeepBidTypeDetailDeepBidType   EventManagerDbtGetV30DataDeepBidTypeDetailDeepBidType = "IAAP_SEVEN_ROI_COEFFICIENT"
	LAYER_ROI_EventManagerDbtGetV30DataDeepBidTypeDetailDeepBidType                    EventManagerDbtGetV30DataDeepBidTypeDetailDeepBidType = "LAYER_ROI"
	LOAN_ROI_EventManagerDbtGetV30DataDeepBidTypeDetailDeepBidType                     EventManagerDbtGetV30DataDeepBidTypeDetailDeepBidType = "LOAN_ROI"
	MIN_SECOND_STAGE_EventManagerDbtGetV30DataDeepBidTypeDetailDeepBidType             EventManagerDbtGetV30DataDeepBidTypeDetailDeepBidType = "MIN_SECOND_STAGE"
	NET_ORDER_EventManagerDbtGetV30DataDeepBidTypeDetailDeepBidType                    EventManagerDbtGetV30DataDeepBidTypeDetailDeepBidType = "NET_ORDER"
	NET_ORDER_ROI_EventManagerDbtGetV30DataDeepBidTypeDetailDeepBidType                EventManagerDbtGetV30DataDeepBidTypeDetailDeepBidType = "NET_ORDER_ROI"
	PACING_SECOND_STAGE_EventManagerDbtGetV30DataDeepBidTypeDetailDeepBidType          EventManagerDbtGetV30DataDeepBidTypeDetailDeepBidType = "PACING_SECOND_STAGE"
	PER_AND_SEVEN_PAY_ROI_EventManagerDbtGetV30DataDeepBidTypeDetailDeepBidType        EventManagerDbtGetV30DataDeepBidTypeDetailDeepBidType = "PER_AND_SEVEN_PAY_ROI"
	PHONE_CONNECT_BID_EventManagerDbtGetV30DataDeepBidTypeDetailDeepBidType            EventManagerDbtGetV30DataDeepBidTypeDetailDeepBidType = "PHONE_CONNECT_BID"
	ROI_COEFFICIENT_EventManagerDbtGetV30DataDeepBidTypeDetailDeepBidType              EventManagerDbtGetV30DataDeepBidTypeDetailDeepBidType = "ROI_COEFFICIENT"
	ROI_DIRECT_MAIL_EventManagerDbtGetV30DataDeepBidTypeDetailDeepBidType              EventManagerDbtGetV30DataDeepBidTypeDetailDeepBidType = "ROI_DIRECT_MAIL"
	ROI_PACING_EventManagerDbtGetV30DataDeepBidTypeDetailDeepBidType                   EventManagerDbtGetV30DataDeepBidTypeDetailDeepBidType = "ROI_PACING"
	RTA_DOUBLE_BID_EventManagerDbtGetV30DataDeepBidTypeDetailDeepBidType               EventManagerDbtGetV30DataDeepBidTypeDetailDeepBidType = "RTA_DOUBLE_BID"
	SEVEN_ROI_COEFFICIENT_EventManagerDbtGetV30DataDeepBidTypeDetailDeepBidType        EventManagerDbtGetV30DataDeepBidTypeDetailDeepBidType = "SEVEN_ROI_COEFFICIENT"
	SMARTBID_EventManagerDbtGetV30DataDeepBidTypeDetailDeepBidType                     EventManagerDbtGetV30DataDeepBidTypeDetailDeepBidType = "SMARTBID"
	SOCIAL_ROI_EventManagerDbtGetV30DataDeepBidTypeDetailDeepBidType                   EventManagerDbtGetV30DataDeepBidTypeDetailDeepBidType = "SOCIAL_ROI"
)

// Ptr returns reference to event_manager_dbt_get_v3.0_data_deep_bid_type_detail_deep_bid_type value
func (v EventManagerDbtGetV30DataDeepBidTypeDetailDeepBidType) Ptr() *EventManagerDbtGetV30DataDeepBidTypeDetailDeepBidType {
	return &v
}
