/*
Oceanengine Open Api

巨量引擎开放平台 Open Api


*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package models

// DpaClueProductListV2FilteringAuditStatus
type DpaClueProductListV2FilteringAuditStatus string

// List of dpa_clue_product_list_v2_filtering_audit_status
const (
	AUDIT_STATUS_APPROVE_DpaClueProductListV2FilteringAuditStatus DpaClueProductListV2FilteringAuditStatus = "AUDIT_STATUS_APPROVE"
	AUDIT_STATUS_INIT_DpaClueProductListV2FilteringAuditStatus    DpaClueProductListV2FilteringAuditStatus = "AUDIT_STATUS_INIT"
	AUDIT_STATUS_REJECT_DpaClueProductListV2FilteringAuditStatus  DpaClueProductListV2FilteringAuditStatus = "AUDIT_STATUS_REJECT"
)

// Ptr returns reference to dpa_clue_product_list_v2_filtering_audit_status value
func (v DpaClueProductListV2FilteringAuditStatus) Ptr() *DpaClueProductListV2FilteringAuditStatus {
	return &v
}
