/*
Oceanengine Open Api

巨量引擎开放平台 Open Api


*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package models

// StdProjectCreateV30AppType
type StdProjectCreateV30AppType string

// List of std_project_create_v3.0_app_type
const (
	ANDROID_StdProjectCreateV30AppType StdProjectCreateV30AppType = "ANDROID"
	IOS_StdProjectCreateV30AppType     StdProjectCreateV30AppType = "IOS"
)

// Ptr returns reference to std_project_create_v3.0_app_type value
func (v StdProjectCreateV30AppType) Ptr() *StdProjectCreateV30AppType {
	return &v
}
