/*
Oceanengine Open Api

巨量引擎开放平台 Open Api


*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package models

// QianchuanOverallVideoUpdateV10MultiProductCreativeListTitleMaterialTitleType
type QianchuanOverallVideoUpdateV10MultiProductCreativeListTitleMaterialTitleType string

// List of qianchuan_overall_video_update_v1.0_multi_product_creative_list_title_material_title_type
const (
	COMMODITY_CARD_QianchuanOverallVideoUpdateV10MultiProductCreativeListTitleMaterialTitleType QianchuanOverallVideoUpdateV10MultiProductCreativeListTitleMaterialTitleType = "COMMODITY_CARD"
	CUSTOM_QianchuanOverallVideoUpdateV10MultiProductCreativeListTitleMaterialTitleType         QianchuanOverallVideoUpdateV10MultiProductCreativeListTitleMaterialTitleType = "CUSTOM"
)

// Ptr returns reference to qianchuan_overall_video_update_v1.0_multi_product_creative_list_title_material_title_type value
func (v QianchuanOverallVideoUpdateV10MultiProductCreativeListTitleMaterialTitleType) Ptr() *QianchuanOverallVideoUpdateV10MultiProductCreativeListTitleMaterialTitleType {
	return &v
}
