/*
Oceanengine Open Api

巨量引擎开放平台 Open Api

API version: 1.1.4
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package models

// ToolsPioneerProgramAttachmentUploadV2ResponseData
type ToolsPioneerProgramAttachmentUploadV2ResponseData struct {
	// 是否上报成功
	Success bool `json:"success"`
}
