/*
Oceanengine Open Api

巨量引擎开放平台 Open Api


*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package models

// ToolsSiteGetV2Status
type ToolsSiteGetV2Status string

// List of tools_site_get_v2_status
const (
	SITE_ALL_ToolsSiteGetV2Status      ToolsSiteGetV2Status = "SITE_ALL"
	SITE_ONLINE_ToolsSiteGetV2Status   ToolsSiteGetV2Status = "SITE_ONLINE"
	SITE_OFFLINE_ToolsSiteGetV2Status  ToolsSiteGetV2Status = "SITE_OFFLINE"
	SITE_REJECTED_ToolsSiteGetV2Status ToolsSiteGetV2Status = "SITE_REJECTED"
	SITE_TRASH_ToolsSiteGetV2Status    ToolsSiteGetV2Status = "SITE_TRASH"
)

// Ptr returns reference to tools_site_get_v2_status value
func (v ToolsSiteGetV2Status) Ptr() *ToolsSiteGetV2Status {
	return &v
}
