/*
Oceanengine Open Api

巨量引擎开放平台 Open Api


*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package models

// FileEbpVideoGetV30ResponseDataListInner struct for FileEbpVideoGetV30ResponseDataListInner
type FileEbpVideoGetV30ResponseDataListInner struct {
	// 码率，单位bps
	BitRate *int64 `json:"bit_rate,omitempty"`
	//
	CreateTime *string `json:"create_time,omitempty"`
	// 素材时长
	Duration *string `json:"duration,omitempty"`
	// 素材文件名
	FileName *string `json:"file_name,omitempty"`
	// 素材宽度
	Height    *int64                               `json:"height,omitempty"`
	ImageMode *FileEbpVideoGetV30DataListImageMode `json:"image_mode,omitempty"`
	// 素材ID
	MaterialId         *int64                                                     `json:"material_id,omitempty"`
	MaterialProperties *FileEbpVideoGetV30ResponseDataListInnerMaterialProperties `json:"material_properties,omitempty"`
	// 视频首帧截图，仅限同主体进行素材预览查看，若非同主体会返回“素材所属主体与开发者主体不一致无法获取URL”
	PosterUrl *string `json:"poster_url,omitempty"`
	// 素材md5
	Signature *string `json:"signature,omitempty"`
	// 素材文件大小
	Size *int64 `json:"size,omitempty"`
	// 视频地址，仅限同主体进行素材预览查看，若非同主体会返回“素材所属主体与开发者主体不一致无法获取URL” 链接仅做预览使用，预览链接有效期为1小时
	Url *string `json:"url,omitempty"`
	// 视频ID
	VideoId *string `json:"video_id,omitempty"`
	// 素材长度
	Width *int64 `json:"width,omitempty"`
}
