/*
Oceanengine Open Api

巨量引擎开放平台 Open Api


*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package models

// LocalProjectListV30FilteringProjectStatusFirst 项目一级状态筛选，默认不限（不包含已删除）  项目一级状态筛选
type LocalProjectListV30FilteringProjectStatusFirst string

// List of local_project_list_v3.0_filtering_project_status_first
const (
	PROJECT_STATUS_ALL_LocalProjectListV30FilteringProjectStatusFirst        LocalProjectListV30FilteringProjectStatusFirst = "PROJECT_STATUS_ALL"
	PROJECT_STATUS_DELETE_LocalProjectListV30FilteringProjectStatusFirst     LocalProjectListV30FilteringProjectStatusFirst = "PROJECT_STATUS_DELETE"
	PROJECT_STATUS_DISABLE_LocalProjectListV30FilteringProjectStatusFirst    LocalProjectListV30FilteringProjectStatusFirst = "PROJECT_STATUS_DISABLE"
	PROJECT_STATUS_DONE_LocalProjectListV30FilteringProjectStatusFirst       LocalProjectListV30FilteringProjectStatusFirst = "PROJECT_STATUS_DONE"
	PROJECT_STATUS_ENABLE_LocalProjectListV30FilteringProjectStatusFirst     LocalProjectListV30FilteringProjectStatusFirst = "PROJECT_STATUS_ENABLE"
	PROJECT_STATUS_NOT_DELETE_LocalProjectListV30FilteringProjectStatusFirst LocalProjectListV30FilteringProjectStatusFirst = "PROJECT_STATUS_NOT_DELETE"
)

// Ptr returns reference to local_project_list_v3.0_filtering_project_status_first value
func (v LocalProjectListV30FilteringProjectStatusFirst) Ptr() *LocalProjectListV30FilteringProjectStatusFirst {
	return &v
}
