/*
Oceanengine Open Api

巨量引擎开放平台 Open Api


*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package models

// QianchuanAdDetailGetV10DataDynamicCreative
type QianchuanAdDetailGetV10DataDynamicCreative int64

// List of qianchuan_ad_detail_get_v1.0_data_dynamic_creative
const (
	Enum_0_QianchuanAdDetailGetV10DataDynamicCreative QianchuanAdDetailGetV10DataDynamicCreative = 0
	Enum_1_QianchuanAdDetailGetV10DataDynamicCreative QianchuanAdDetailGetV10DataDynamicCreative = 1
)

// Ptr returns reference to qianchuan_ad_detail_get_v1.0_data_dynamic_creative value
func (v QianchuanAdDetailGetV10DataDynamicCreative) Ptr() *QianchuanAdDetailGetV10DataDynamicCreative {
	return &v
}
