/*
Oceanengine Open Api

巨量引擎开放平台 Open Api


*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package models

// ToolsSiteTemplateCreateV2DataBricksButtonAppointEventLinkLinkType 链接类型，当`link`不为空时，有值
type ToolsSiteTemplateCreateV2DataBricksButtonAppointEventLinkLinkType string

// List of tools_site_template_create_v2_data_bricks_button_appoint_event_link_link_type
const (
	QUICK_APP_ToolsSiteTemplateCreateV2DataBricksButtonAppointEventLinkLinkType ToolsSiteTemplateCreateV2DataBricksButtonAppointEventLinkLinkType = "QUICK_APP"
	SCHEME_ToolsSiteTemplateCreateV2DataBricksButtonAppointEventLinkLinkType    ToolsSiteTemplateCreateV2DataBricksButtonAppointEventLinkLinkType = "SCHEME"
	URL_ToolsSiteTemplateCreateV2DataBricksButtonAppointEventLinkLinkType       ToolsSiteTemplateCreateV2DataBricksButtonAppointEventLinkLinkType = "URL"
)

// Ptr returns reference to tools_site_template_create_v2_data_bricks_button_appoint_event_link_link_type value
func (v ToolsSiteTemplateCreateV2DataBricksButtonAppointEventLinkLinkType) Ptr() *ToolsSiteTemplateCreateV2DataBricksButtonAppointEventLinkLinkType {
	return &v
}
