/*
Oceanengine Open Api

巨量引擎开放平台 Open Api


*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package models

// CreativeDetailGetV30ResponseDataCreativeAbstractMaterialsInner struct for CreativeDetailGetV30ResponseDataCreativeAbstractMaterialsInner
type CreativeDetailGetV30ResponseDataCreativeAbstractMaterialsInner struct {
	StructAbstractInfo *CreativeDetailGetV30ResponseDataCreativeAbstractMaterialsInnerStructAbstractInfo `json:"struct_abstract_info,omitempty"`
	TextAbstractInfo   *CreativeDetailGetV30ResponseDataCreativeAbstractMaterialsInnerTextAbstractInfo   `json:"text_abstract_info,omitempty"`
}
