/*
Oceanengine Open Api

巨量引擎开放平台 Open Api


*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package models

// ToolsSiteTemplateSiteCreateV2BricksButtonAppointEventLinkLinkType 链接类型，当图片跳转链接信息不为空时，必填
type ToolsSiteTemplateSiteCreateV2BricksButtonAppointEventLinkLinkType string

// List of tools_site_template_site_create_v2_bricks_button_appoint_event_link_link_type
const (
	QUICK_APP_ToolsSiteTemplateSiteCreateV2BricksButtonAppointEventLinkLinkType ToolsSiteTemplateSiteCreateV2BricksButtonAppointEventLinkLinkType = "QUICK_APP"
	SCHEME_ToolsSiteTemplateSiteCreateV2BricksButtonAppointEventLinkLinkType    ToolsSiteTemplateSiteCreateV2BricksButtonAppointEventLinkLinkType = "SCHEME"
	URL_ToolsSiteTemplateSiteCreateV2BricksButtonAppointEventLinkLinkType       ToolsSiteTemplateSiteCreateV2BricksButtonAppointEventLinkLinkType = "URL"
)

// Ptr returns reference to tools_site_template_site_create_v2_bricks_button_appoint_event_link_link_type value
func (v ToolsSiteTemplateSiteCreateV2BricksButtonAppointEventLinkLinkType) Ptr() *ToolsSiteTemplateSiteCreateV2BricksButtonAppointEventLinkLinkType {
	return &v
}
