/*
Oceanengine Open Api

巨量引擎开放平台 Open Api


*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package models

// ToolsEbpMaterialListV30ResponseDataData
type ToolsEbpMaterialListV30ResponseDataData struct {
	//
	Videos []*ToolsEbpMaterialListV30ResponseDataDataVideosInner `json:"videos,omitempty"`
}
