/*
Oceanengine Open Api

巨量引擎开放平台 Open Api


*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package models

// BrandMaOrderListV30ResponseDataOrdersInnerAdInfosInner struct for BrandMaOrderListV30ResponseDataOrdersInnerAdInfosInner
type BrandMaOrderListV30ResponseDataOrdersInnerAdInfosInner struct {
	// 计划ID
	AdId *int64 `json:"ad_id,omitempty"`
	// 计划投放日期
	Date *string `json:"date,omitempty"`
	// 计划投放实际结束时间
	RealEndTime *string `json:"real_end_time,omitempty"`
	// 计划投放实际开始时间
	RealStartTime *string `json:"real_start_time,omitempty"`
}
