/*
Oceanengine Open Api

巨量引擎开放平台 Open Api


*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package models

// QianchuanTodayLiveV2RoomUserGetV10FlowSource
type QianchuanTodayLiveV2RoomUserGetV10FlowSource string

// List of qianchuan_today_live_v2_room_user_get_v1.0_flow_source
const (
	ALL_QianchuanTodayLiveV2RoomUserGetV10FlowSource QianchuanTodayLiveV2RoomUserGetV10FlowSource = "ALL"
	PC_QianchuanTodayLiveV2RoomUserGetV10FlowSource  QianchuanTodayLiveV2RoomUserGetV10FlowSource = "PC"
)

// Ptr returns reference to qianchuan_today_live_v2_room_user_get_v1.0_flow_source value
func (v QianchuanTodayLiveV2RoomUserGetV10FlowSource) Ptr() *QianchuanTodayLiveV2RoomUserGetV10FlowSource {
	return &v
}
