/*
Oceanengine Open Api

巨量引擎开放平台 Open Api


*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package models

// ProjectUpdateV30KeywordsBidType
type ProjectUpdateV30KeywordsBidType string

// List of project_update_v3.0_keywords_bid_type
const (
	FEED_TO_SEARCH_ProjectUpdateV30KeywordsBidType ProjectUpdateV30KeywordsBidType = "FEED_TO_SEARCH"
)

// Ptr returns reference to project_update_v3.0_keywords_bid_type value
func (v ProjectUpdateV30KeywordsBidType) Ptr() *ProjectUpdateV30KeywordsBidType {
	return &v
}
