/*
Oceanengine Open Api

巨量引擎开放平台 Open Api


*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package models

// ToolsEbpAppExtendCreateV30AccountType 操作类型 BP/AD
type ToolsEbpAppExtendCreateV30AccountType string

// List of tools_ebp_app_extend_create_v3.0_account_type
const (
	BP_ToolsEbpAppExtendCreateV30AccountType  ToolsEbpAppExtendCreateV30AccountType = "BP"
	EBP_ToolsEbpAppExtendCreateV30AccountType ToolsEbpAppExtendCreateV30AccountType = "EBP"
)

// Ptr returns reference to tools_ebp_app_extend_create_v3.0_account_type value
func (v ToolsEbpAppExtendCreateV30AccountType) Ptr() *ToolsEbpAppExtendCreateV30AccountType {
	return &v
}
