/*
Oceanengine Open Api

巨量引擎开放平台 Open Api


*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package models

// PromotionDeepbidUpdateV30RequestDataInner struct for PromotionDeepbidUpdateV30RequestDataInner
type PromotionDeepbidUpdateV30RequestDataInner struct {
	//
	Deepbid float64 `json:"deepbid"`
	//
	PromotionId int64 `json:"promotion_id"`
}
