/*
Oceanengine Open Api

巨量引擎开放平台 Open Api


*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package models

// AdvertiserPublicInfoV2ResponseData struct for AdvertiserPublicInfoV2ResponseData
type AdvertiserPublicInfoV2ResponseData struct {
	//
	Company *string `json:"company,omitempty"`
	//
	FirstIndustryName *string `json:"first_industry_name,omitempty"`
	//
	Id *int64 `json:"id,omitempty"`
	//
	Name *string `json:"name,omitempty"`
	//
	SecondIndustryName *string `json:"second_industry_name,omitempty"`
}
