/*
Oceanengine Open Api

巨量引擎开放平台 Open Api


*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package models

// StarVasCreateBoostItemGroupV2BoostType 加热方式
type StarVasCreateBoostItemGroupV2BoostType string

// List of star_vas_create_boost_item_group_v2_boost_type
const (
	CUSTOM_PACKAGE_StarVasCreateBoostItemGroupV2BoostType StarVasCreateBoostItemGroupV2BoostType = "CUSTOM_PACKAGE"
	CUSTOM_TAG_StarVasCreateBoostItemGroupV2BoostType     StarVasCreateBoostItemGroupV2BoostType = "CUSTOM_TAG"
	NONE_StarVasCreateBoostItemGroupV2BoostType           StarVasCreateBoostItemGroupV2BoostType = "NONE"
)

// Ptr returns reference to star_vas_create_boost_item_group_v2_boost_type value
func (v StarVasCreateBoostItemGroupV2BoostType) Ptr() *StarVasCreateBoostItemGroupV2BoostType {
	return &v
}
