/*
Oceanengine Open Api

巨量引擎开放平台 Open Api


*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package models

// ToolsAppIosListV2Filtering
type ToolsAppIosListV2Filtering struct {
	//
	SearchKey *string                           `json:"search_key,omitempty"`
	Status    *ToolsAppIosListV2FilteringStatus `json:"status,omitempty"`
}
