/*
Oceanengine Open Api

巨量引擎开放平台 Open Api


*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package models

// ToolsAppManagementExtendPackageListV2V2FilteringStatus
type ToolsAppManagementExtendPackageListV2V2FilteringStatus string

// List of tools_app_management_extend_package_list_v2_v2_filtering_status
const (
	ALL_ToolsAppManagementExtendPackageListV2V2FilteringStatus             ToolsAppManagementExtendPackageListV2V2FilteringStatus = "ALL"
	NOT_UPDATE_ToolsAppManagementExtendPackageListV2V2FilteringStatus      ToolsAppManagementExtendPackageListV2V2FilteringStatus = "NOT_UPDATE"
	CREATING_ToolsAppManagementExtendPackageListV2V2FilteringStatus        ToolsAppManagementExtendPackageListV2V2FilteringStatus = "CREATING"
	UPDATING_ToolsAppManagementExtendPackageListV2V2FilteringStatus        ToolsAppManagementExtendPackageListV2V2FilteringStatus = "UPDATING"
	ENABLE_ToolsAppManagementExtendPackageListV2V2FilteringStatus          ToolsAppManagementExtendPackageListV2V2FilteringStatus = "ENABLE"
	CREATION_FAILED_ToolsAppManagementExtendPackageListV2V2FilteringStatus ToolsAppManagementExtendPackageListV2V2FilteringStatus = "CREATION_FAILED"
	UPDATE_FAILED_ToolsAppManagementExtendPackageListV2V2FilteringStatus   ToolsAppManagementExtendPackageListV2V2FilteringStatus = "UPDATE_FAILED"
	PUBLISHED_ToolsAppManagementExtendPackageListV2V2FilteringStatus       ToolsAppManagementExtendPackageListV2V2FilteringStatus = "PUBLISHED"
)

// Ptr returns reference to tools_app_management_extend_package_list_v2_v2_filtering_status value
func (v ToolsAppManagementExtendPackageListV2V2FilteringStatus) Ptr() *ToolsAppManagementExtendPackageListV2V2FilteringStatus {
	return &v
}
