/*
Oceanengine Open Api

巨量引擎开放平台 Open Api


*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package models

// AicElementGetV30Filtering
type AicElementGetV30Filtering struct {
	// 根据元素创建时间进行过滤结束始时间，与create_start_time搭配使用 格式为yyyy-mm-dd HH:MM:SS
	CreateEndTime *string `json:"create_end_time,omitempty"`
	// 根据元素创建时间进行过滤的起始时间，与create_end_time搭配使用 格式为yyyy-mm-dd HH:MM:SS
	CreateStartTime *string `json:"create_start_time,omitempty"`
	// 元素id列表，数量限制：50
	ElementIds []int64 `json:"element_ids,omitempty"`
	// 元素名称，模糊匹配
	ElementName *string                               `json:"element_name,omitempty"`
	ElementType *AicElementGetV30FilteringElementType `json:"element_type,omitempty"`
	// 元素的存储路径（文件夹） 传入后仅查询文件夹下素材，示例：/数码/电脑，/为根路径，最大层级不得超过10
	PathName *string                         `json:"path_name,omitempty"`
	UseAs    *AicElementGetV30FilteringUseAs `json:"use_as,omitempty"`
}
