/*
Oceanengine Open Api

巨量引擎开放平台 Open Api


*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package models

// ToolsAppManagementAndroidBasicPackagePublishV2AccountType 账号类型
type ToolsAppManagementAndroidBasicPackagePublishV2AccountType string

// List of tools_app_management_android_basic_package_publish_v2_account_type
const (
	AD_ToolsAppManagementAndroidBasicPackagePublishV2AccountType ToolsAppManagementAndroidBasicPackagePublishV2AccountType = "AD"
	BP_ToolsAppManagementAndroidBasicPackagePublishV2AccountType ToolsAppManagementAndroidBasicPackagePublishV2AccountType = "BP"
)

// Ptr returns reference to tools_app_management_android_basic_package_publish_v2_account_type value
func (v ToolsAppManagementAndroidBasicPackagePublishV2AccountType) Ptr() *ToolsAppManagementAndroidBasicPackagePublishV2AccountType {
	return &v
}
