/*
Oceanengine Open Api

巨量引擎开放平台 Open Api


*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package models

// ToolsCountryInfoV2Language
type ToolsCountryInfoV2Language string

// List of tools_country_info_v2_language
const (
	ZH_CN_ToolsCountryInfoV2Language     ToolsCountryInfoV2Language = "ZH_CN"
	ZH_CN_GOV_ToolsCountryInfoV2Language ToolsCountryInfoV2Language = "ZH_CN_GOV"
)

// Ptr returns reference to tools_country_info_v2_language value
func (v ToolsCountryInfoV2Language) Ptr() *ToolsCountryInfoV2Language {
	return &v
}
