/*
Oceanengine Open Api

巨量引擎开放平台 Open Api


*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package models

// StarCopyrightGetV2ResponseDataNovelListInnerCopyrightQualificationInner struct for StarCopyrightGetV2ResponseDataNovelListInnerCopyrightQualificationInner
type StarCopyrightGetV2ResponseDataNovelListInnerCopyrightQualificationInner struct {
	// 文件名称
	FileName *string `json:"file_name,omitempty"`
	// 文件链接
	FileUri *string `json:"file_uri,omitempty"`
}
