/*
Oceanengine Open Api

巨量引擎开放平台 Open Api


*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package models

// BrandMaterialUpdateV30RequestMaterialListInnerMaterialComponentAwemeVideoVideo
type BrandMaterialUpdateV30RequestMaterialListInnerMaterialComponentAwemeVideoVideo struct {
	// 视频原始id
	VideoId *string `json:"video_id,omitempty"`
}
