/*
Oceanengine Open Api

巨量引擎开放平台 Open Api


*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package models

// ToolsBidSuggestV2SuperiorPopularityType
type ToolsBidSuggestV2SuperiorPopularityType string

// List of tools_bid_suggest_v2_superior_popularity_type
const (
	NONE_ToolsBidSuggestV2SuperiorPopularityType ToolsBidSuggestV2SuperiorPopularityType = "NONE"
	GAME_ToolsBidSuggestV2SuperiorPopularityType ToolsBidSuggestV2SuperiorPopularityType = "GAME"
)

// Ptr returns reference to tools_bid_suggest_v2_superior_popularity_type value
func (v ToolsBidSuggestV2SuperiorPopularityType) Ptr() *ToolsBidSuggestV2SuperiorPopularityType {
	return &v
}
