/*
Oceanengine Open Api

巨量引擎开放平台 Open Api


*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package models

// ToolsEbpMicroAppletUpdateV30Request struct for ToolsEbpMicroAppletUpdateV30Request
type ToolsEbpMicroAppletUpdateV30Request struct {
	//
	AccountId   int64                                   `json:"account_id"`
	AccountType ToolsEbpMicroAppletUpdateV30AccountType `json:"account_type"`
	// 主成分字段
	Data map[string]string `json:"data"`
	//
	InstanceId int64 `json:"instance_id"`
	//
	Remark *string `json:"remark,omitempty"`
	//
	SchemaInfo []*ToolsEbpMicroAppletUpdateV30RequestSchemaInfoInner `json:"schema_info"`
}
