/*
Oceanengine Open Api

巨量引擎开放平台 Open Api


*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package models

// BrandOrderCancelDeleteV30ResponseData
type BrandOrderCancelDeleteV30ResponseData struct {
	//
	OrderId *int64 `json:"order_id,omitempty"`
}
