/*
Oceanengine Open Api

巨量引擎开放平台 Open Api


*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package models

// QianchuanUniPromotionAdControlTaskStatusUpdateV10ResponseDataErrorsInner struct for QianchuanUniPromotionAdControlTaskStatusUpdateV10ResponseDataErrorsInner
type QianchuanUniPromotionAdControlTaskStatusUpdateV10ResponseDataErrorsInner struct {
	// 更新失败任务的原因
	ErrorMessage *string `json:"error_message,omitempty"`
	// 更新失败的任务id
	TaskId *int64 `json:"task_id,omitempty"`
}
