/*
Oceanengine Open Api

巨量引擎开放平台 Open Api


*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package models

// ReportAdGetV2DataListCampaignType
type ReportAdGetV2DataListCampaignType string

// List of report_ad_get_v2_data_list_campaign_type
const (
	FEED_ReportAdGetV2DataListCampaignType   ReportAdGetV2DataListCampaignType = "FEED"
	SEARCH_ReportAdGetV2DataListCampaignType ReportAdGetV2DataListCampaignType = "SEARCH"
)

// Ptr returns reference to report_ad_get_v2_data_list_campaign_type value
func (v ReportAdGetV2DataListCampaignType) Ptr() *ReportAdGetV2DataListCampaignType {
	return &v
}
