/*
Oceanengine Open Api

巨量引擎开放平台 Open Api


*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package models

// StarMcnProviderGetTaskDetailV2ResponseDataTaskDetailInfoRelationObjectInfoInner struct for StarMcnProviderGetTaskDetailV2ResponseDataTaskDetailInfoRelationObjectInfoInner
type StarMcnProviderGetTaskDetailV2ResponseDataTaskDetailInfoRelationObjectInfoInner struct {
	ObjectFieldInfo *StarMcnProviderGetTaskDetailV2ResponseDataTaskDetailInfoRelationObjectInfoInnerObjectFieldInfo `json:"object_field_info,omitempty"`
	//
	ObjectId *int64 `json:"object_id,omitempty"`
	//
	StarObjectType *int64 `json:"star_object_type,omitempty"`
}
