/*
Oceanengine Open Api

巨量引擎开放平台 Open Api


*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package models

// FileRebateMaterialDownloadCreateTaskV2MaterialPolicyType 素材政策类型
type FileRebateMaterialDownloadCreateTaskV2MaterialPolicyType string

// List of file_rebate_material_download_create_task_v2_material_policy_type
const (
	VALID_ORIGINAL_MATERIAL_RATE_FileRebateMaterialDownloadCreateTaskV2MaterialPolicyType   FileRebateMaterialDownloadCreateTaskV2MaterialPolicyType = "VALID_ORIGINAL_MATERIAL_RATE"
	VALID_FIRST_EFFECTIVE_MATERIAL_FileRebateMaterialDownloadCreateTaskV2MaterialPolicyType FileRebateMaterialDownloadCreateTaskV2MaterialPolicyType = "VALID_FIRST_EFFECTIVE_MATERIAL"
	VALID_HIGH_QUALITY_MATERIAL_FileRebateMaterialDownloadCreateTaskV2MaterialPolicyType    FileRebateMaterialDownloadCreateTaskV2MaterialPolicyType = "VALID_HIGH_QUALITY_MATERIAL"
)

// Ptr returns reference to file_rebate_material_download_create_task_v2_material_policy_type value
func (v FileRebateMaterialDownloadCreateTaskV2MaterialPolicyType) Ptr() *FileRebateMaterialDownloadCreateTaskV2MaterialPolicyType {
	return &v
}
