/*
Oceanengine Open Api

巨量引擎开放平台 Open Api


*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package models

// PenaltyTaskGetV30DataPenaltyTaskListTaskStatus 扣罚任务单状态（详见：客户违规扣罚任务单状态）
type PenaltyTaskGetV30DataPenaltyTaskListTaskStatus string

// List of penalty_task_get_v3.0_data_penalty_task_list_task_status
const (
	APPEAL_FINISH_PenaltyTaskGetV30DataPenaltyTaskListTaskStatus            PenaltyTaskGetV30DataPenaltyTaskListTaskStatus = "APPEAL_FINISH"
	APPEAL_ING_PenaltyTaskGetV30DataPenaltyTaskListTaskStatus               PenaltyTaskGetV30DataPenaltyTaskListTaskStatus = "APPEAL_ING"
	BUSINESS_SECURITY_APPEAL_PenaltyTaskGetV30DataPenaltyTaskListTaskStatus PenaltyTaskGetV30DataPenaltyTaskListTaskStatus = "BUSINESS_SECURITY_APPEAL"
	CONFIRM_PenaltyTaskGetV30DataPenaltyTaskListTaskStatus                  PenaltyTaskGetV30DataPenaltyTaskListTaskStatus = "CONFIRM"
	CONTEXT_WAITING_PenaltyTaskGetV30DataPenaltyTaskListTaskStatus          PenaltyTaskGetV30DataPenaltyTaskListTaskStatus = "CONTEXT_WAITING"
	INIT_PenaltyTaskGetV30DataPenaltyTaskListTaskStatus                     PenaltyTaskGetV30DataPenaltyTaskListTaskStatus = "INIT"
	PENALTY_PART_PenaltyTaskGetV30DataPenaltyTaskListTaskStatus             PenaltyTaskGetV30DataPenaltyTaskListTaskStatus = "PENALTY_PART"
	PENALTY_PAUSE_PenaltyTaskGetV30DataPenaltyTaskListTaskStatus            PenaltyTaskGetV30DataPenaltyTaskListTaskStatus = "PENALTY_PAUSE"
	PENALTY_SUCCESS_PenaltyTaskGetV30DataPenaltyTaskListTaskStatus          PenaltyTaskGetV30DataPenaltyTaskListTaskStatus = "PENALTY_SUCCESS"
	TERMINAL_PenaltyTaskGetV30DataPenaltyTaskListTaskStatus                 PenaltyTaskGetV30DataPenaltyTaskListTaskStatus = "TERMINAL"
	WAIT_CONFIRM_PenaltyTaskGetV30DataPenaltyTaskListTaskStatus             PenaltyTaskGetV30DataPenaltyTaskListTaskStatus = "WAIT_CONFIRM"
)

// Ptr returns reference to penalty_task_get_v3.0_data_penalty_task_list_task_status value
func (v PenaltyTaskGetV30DataPenaltyTaskListTaskStatus) Ptr() *PenaltyTaskGetV30DataPenaltyTaskListTaskStatus {
	return &v
}
