/*
Oceanengine Open Api

巨量引擎开放平台 Open Api


*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package models

// ClueCouponDetailV2DataFormExtendInfoCountConfigCountType
type ClueCouponDetailV2DataFormExtendInfoCountConfigCountType string

// List of clue_coupon_detail_v2_data_form_extend_info_count_config_count_type
const (
	COUNT_TYPE_INCREMENT_ClueCouponDetailV2DataFormExtendInfoCountConfigCountType ClueCouponDetailV2DataFormExtendInfoCountConfigCountType = "COUNT_TYPE_INCREMENT"
	COUNT_TYPE_DECREMENT_ClueCouponDetailV2DataFormExtendInfoCountConfigCountType ClueCouponDetailV2DataFormExtendInfoCountConfigCountType = "COUNT_TYPE_DECREMENT"
)

// Ptr returns reference to clue_coupon_detail_v2_data_form_extend_info_count_config_count_type value
func (v ClueCouponDetailV2DataFormExtendInfoCountConfigCountType) Ptr() *ClueCouponDetailV2DataFormExtendInfoCountConfigCountType {
	return &v
}
