/*
Oceanengine Open Api

巨量引擎开放平台 Open Api

API version: 1.0.17
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package models

import (
	"fmt"
)

// QianchuanProductAnalyseCompareCreativeV10TimeRange
type QianchuanProductAnalyseCompareCreativeV10TimeRange int64

// List of qianchuan_product_analyse_compare_creative_v1.0_time_range
const (
	Enum_15_QianchuanProductAnalyseCompareCreativeV10TimeRange QianchuanProductAnalyseCompareCreativeV10TimeRange = 15
	Enum_30_QianchuanProductAnalyseCompareCreativeV10TimeRange QianchuanProductAnalyseCompareCreativeV10TimeRange = 30
	Enum_7_QianchuanProductAnalyseCompareCreativeV10TimeRange  QianchuanProductAnalyseCompareCreativeV10TimeRange = 7
)

// All allowed values of QianchuanProductAnalyseCompareCreativeV10TimeRange enum
var AllowedQianchuanProductAnalyseCompareCreativeV10TimeRangeEnumValues = []QianchuanProductAnalyseCompareCreativeV10TimeRange{
	15,
	30,
	7,
}

// NewQianchuanProductAnalyseCompareCreativeV10TimeRangeFromValue returns a pointer to a valid QianchuanProductAnalyseCompareCreativeV10TimeRange
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewQianchuanProductAnalyseCompareCreativeV10TimeRangeFromValue(v int64) (*QianchuanProductAnalyseCompareCreativeV10TimeRange, error) {
	ev := QianchuanProductAnalyseCompareCreativeV10TimeRange(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for QianchuanProductAnalyseCompareCreativeV10TimeRange: valid values are %v", v, AllowedQianchuanProductAnalyseCompareCreativeV10TimeRangeEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v QianchuanProductAnalyseCompareCreativeV10TimeRange) IsValid() bool {
	for _, existing := range AllowedQianchuanProductAnalyseCompareCreativeV10TimeRangeEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to qianchuan_product_analyse_compare_creative_v1.0_time_range value
func (v QianchuanProductAnalyseCompareCreativeV10TimeRange) Ptr() *QianchuanProductAnalyseCompareCreativeV10TimeRange {
	return &v
}
