/*
Oceanengine Open Api

巨量引擎开放平台 Open Api


*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package models

// CampaignUpdateStatusV2OptStatus
type CampaignUpdateStatusV2OptStatus string

// List of campaign_update_status_v2_opt_status
const (
	DISABLE_CampaignUpdateStatusV2OptStatus CampaignUpdateStatusV2OptStatus = "disable"
	ENABLE_CampaignUpdateStatusV2OptStatus  CampaignUpdateStatusV2OptStatus = "enable"
	DELETE_CampaignUpdateStatusV2OptStatus  CampaignUpdateStatusV2OptStatus = "delete"
)

// Ptr returns reference to campaign_update_status_v2_opt_status value
func (v CampaignUpdateStatusV2OptStatus) Ptr() *CampaignUpdateStatusV2OptStatus {
	return &v
}
