/*
Oceanengine Open Api

巨量引擎开放平台 Open Api


*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package models

// ToolsPrivativeWordAdUpdateV2ResponseData
type ToolsPrivativeWordAdUpdateV2ResponseData struct {
	//
	AdId *int64 `json:"ad_id,omitempty"`
}
