/*
Oceanengine Open Api

巨量引擎开放平台 Open Api


*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package models

// ToolsClueRefundInfoQueryV2ResponseDataInfoInner struct for ToolsClueRefundInfoQueryV2ResponseDataInfoInner
type ToolsClueRefundInfoQueryV2ResponseDataInfoInner struct {
	// 线索ID
	ClueId *int64 `json:"clue_id,omitempty"`
	// 线索是否参与返款标识
	HasQualification *int32 `json:"has_qualification,omitempty"`
	// 返款进度是否结束标识
	IsFinished *int32 `json:"is_finished,omitempty"`
	// 返款小阶段过期时间，单位为毫秒级unix timestamp。
	OverdueTimestamps []int64 `json:"overdue_timestamps,omitempty"`
	// 返款规定合规呼叫总次数
	TotalCallCnt *int32 `json:"total_call_cnt,omitempty"`
	// 符合返款要求呼叫次数
	ValidCallCnt *int32 `json:"valid_call_cnt,omitempty"`
}
