/*
Oceanengine Open Api

巨量引擎开放平台 Open Api


*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package models

// OcProjectMaterialGetV30DataCarouselMaterialListMaterialStatusSecond
type OcProjectMaterialGetV30DataCarouselMaterialListMaterialStatusSecond string

// List of oc_project_material_get_v3.0_data_carousel_material_list_material_status_second
const (
	ACCOUNT_AVATAR_NOT_AVAILABLE_FOR_DELIVERY_OcProjectMaterialGetV30DataCarouselMaterialListMaterialStatusSecond OcProjectMaterialGetV30DataCarouselMaterialListMaterialStatusSecond = "ACCOUNT_AVATAR_NOT_AVAILABLE_FOR_DELIVERY"
	APP_NOT_AVAILABLE_FOR_DELIVERY_OcProjectMaterialGetV30DataCarouselMaterialListMaterialStatusSecond            OcProjectMaterialGetV30DataCarouselMaterialListMaterialStatusSecond = "APP_NOT_AVAILABLE_FOR_DELIVERY"
	DOUYIN_ITEM_NOT_AVAILABLE_FOR_DELIVERY_OcProjectMaterialGetV30DataCarouselMaterialListMaterialStatusSecond    OcProjectMaterialGetV30DataCarouselMaterialListMaterialStatusSecond = "DOUYIN_ITEM_NOT_AVAILABLE_FOR_DELIVERY"
	GUIDE_VIDEO_NOT_EXIST_OcProjectMaterialGetV30DataCarouselMaterialListMaterialStatusSecond                     OcProjectMaterialGetV30DataCarouselMaterialListMaterialStatusSecond = "GUIDE_VIDEO_NOT_EXIST"
	LACK_BASIC_MATERIAL_STATUS_OcProjectMaterialGetV30DataCarouselMaterialListMaterialStatusSecond                OcProjectMaterialGetV30DataCarouselMaterialListMaterialStatusSecond = "LACK_BASIC_MATERIAL_STATUS"
	LIVE_ROOM_NOT_AVAILABLE_FOR_DELIVERY_OcProjectMaterialGetV30DataCarouselMaterialListMaterialStatusSecond      OcProjectMaterialGetV30DataCarouselMaterialListMaterialStatusSecond = "LIVE_ROOM_NOT_AVAILABLE_FOR_DELIVERY"
	MATERIAL_STATUS_AUDIT_OcProjectMaterialGetV30DataCarouselMaterialListMaterialStatusSecond                     OcProjectMaterialGetV30DataCarouselMaterialListMaterialStatusSecond = "MATERIAL_STATUS_AUDIT"
	MATERIAL_STATUS_AWEME_ACCOUNT_OFFLINE_OcProjectMaterialGetV30DataCarouselMaterialListMaterialStatusSecond     OcProjectMaterialGetV30DataCarouselMaterialListMaterialStatusSecond = "MATERIAL_STATUS_AWEME_ACCOUNT_OFFLINE"
	MATERIAL_STATUS_DELETE_OcProjectMaterialGetV30DataCarouselMaterialListMaterialStatusSecond                    OcProjectMaterialGetV30DataCarouselMaterialListMaterialStatusSecond = "MATERIAL_STATUS_DELETE"
	MATERIAL_STATUS_DISABLE_OcProjectMaterialGetV30DataCarouselMaterialListMaterialStatusSecond                   OcProjectMaterialGetV30DataCarouselMaterialListMaterialStatusSecond = "MATERIAL_STATUS_DISABLE"
	MATERIAL_STATUS_FROZEN_OcProjectMaterialGetV30DataCarouselMaterialListMaterialStatusSecond                    OcProjectMaterialGetV30DataCarouselMaterialListMaterialStatusSecond = "MATERIAL_STATUS_FROZEN"
	MATERIAL_STATUS_NO_SCHEDULE_OcProjectMaterialGetV30DataCarouselMaterialListMaterialStatusSecond               OcProjectMaterialGetV30DataCarouselMaterialListMaterialStatusSecond = "MATERIAL_STATUS_NO_SCHEDULE"
	MATERIAL_STATUS_OFFLINE_AUDIT_OcProjectMaterialGetV30DataCarouselMaterialListMaterialStatusSecond             OcProjectMaterialGetV30DataCarouselMaterialListMaterialStatusSecond = "MATERIAL_STATUS_OFFLINE_AUDIT"
	MATERIAL_STATUS_OFFLINE_BALANCE_OcProjectMaterialGetV30DataCarouselMaterialListMaterialStatusSecond           OcProjectMaterialGetV30DataCarouselMaterialListMaterialStatusSecond = "MATERIAL_STATUS_OFFLINE_BALANCE"
	MATERIAL_STATUS_OFFLINE_BUDGET_OcProjectMaterialGetV30DataCarouselMaterialListMaterialStatusSecond            OcProjectMaterialGetV30DataCarouselMaterialListMaterialStatusSecond = "MATERIAL_STATUS_OFFLINE_BUDGET"
	MATERIAL_STATUS_PROCEDURAL_DISABLE_OcProjectMaterialGetV30DataCarouselMaterialListMaterialStatusSecond        OcProjectMaterialGetV30DataCarouselMaterialListMaterialStatusSecond = "MATERIAL_STATUS_PROCEDURAL_DISABLE"
	MATERIAL_STATUS_PRODUCT_OFFLINE_OcProjectMaterialGetV30DataCarouselMaterialListMaterialStatusSecond           OcProjectMaterialGetV30DataCarouselMaterialListMaterialStatusSecond = "MATERIAL_STATUS_PRODUCT_OFFLINE"
	MATERIAL_STATUS_PROJECT_DISABLE_OcProjectMaterialGetV30DataCarouselMaterialListMaterialStatusSecond           OcProjectMaterialGetV30DataCarouselMaterialListMaterialStatusSecond = "MATERIAL_STATUS_PROJECT_DISABLE"
	MATERIAL_STATUS_PROJECT_OFFLINE_BUDGET_OcProjectMaterialGetV30DataCarouselMaterialListMaterialStatusSecond    OcProjectMaterialGetV30DataCarouselMaterialListMaterialStatusSecond = "MATERIAL_STATUS_PROJECT_OFFLINE_BUDGET"
	MATERIAL_STATUS_TIME_NO_REACH_OcProjectMaterialGetV30DataCarouselMaterialListMaterialStatusSecond             OcProjectMaterialGetV30DataCarouselMaterialListMaterialStatusSecond = "MATERIAL_STATUS_TIME_NO_REACH"
	PROJECT_AUDIT_REJECTED_OcProjectMaterialGetV30DataCarouselMaterialListMaterialStatusSecond                    OcProjectMaterialGetV30DataCarouselMaterialListMaterialStatusSecond = "PROJECT_AUDIT_REJECTED"
	PROJECT_REACHED_DELIVERY_DURATION_OcProjectMaterialGetV30DataCarouselMaterialListMaterialStatusSecond         OcProjectMaterialGetV30DataCarouselMaterialListMaterialStatusSecond = "PROJECT_REACHED_DELIVERY_DURATION"
	PROJECT_STATUS_AUDIT_OcProjectMaterialGetV30DataCarouselMaterialListMaterialStatusSecond                      OcProjectMaterialGetV30DataCarouselMaterialListMaterialStatusSecond = "PROJECT_STATUS_AUDIT"
	PROJECT_STATUS_DELETE_OcProjectMaterialGetV30DataCarouselMaterialListMaterialStatusSecond                     OcProjectMaterialGetV30DataCarouselMaterialListMaterialStatusSecond = "PROJECT_STATUS_DELETE"
	PROJECT_STATUS_FROZEN_OcProjectMaterialGetV30DataCarouselMaterialListMaterialStatusSecond                     OcProjectMaterialGetV30DataCarouselMaterialListMaterialStatusSecond = "PROJECT_STATUS_FROZEN"
	PROJECT_STATUS_REAUDIT_OcProjectMaterialGetV30DataCarouselMaterialListMaterialStatusSecond                    OcProjectMaterialGetV30DataCarouselMaterialListMaterialStatusSecond = "PROJECT_STATUS_REAUDIT"
	SHARED_WALLET_EXCEEDS_BUDGET_OcProjectMaterialGetV30DataCarouselMaterialListMaterialStatusSecond              OcProjectMaterialGetV30DataCarouselMaterialListMaterialStatusSecond = "SHARED_WALLET_EXCEEDS_BUDGET"
)

// Ptr returns reference to oc_project_material_get_v3.0_data_carousel_material_list_material_status_second value
func (v OcProjectMaterialGetV30DataCarouselMaterialListMaterialStatusSecond) Ptr() *OcProjectMaterialGetV30DataCarouselMaterialListMaterialStatusSecond {
	return &v
}
